"""
AI-Parrot Tools & Toolkits package.

TOOL_REGISTRY maps tool names to their dotted import paths.
This enables lazy discovery without importing any tool modules at startup.

Auto-generated by: scripts/generate_tool_registry.py
Manual additions are also supported — the script preserves manual entries.
"""

TOOL_REGISTRY: dict[str, str] = {
    # --- Toolkits (Batch 1 — simple tools) ---
    "zipcode": "parrot_tools.zipcode.ZipcodeAPIToolkit",
    "ddgo": "parrot_tools.ddgo.DuckDuckGoToolkit",
    "reddit": "parrot_tools.reddit.RedditToolkit",
    "msteams": "parrot_tools.msteams.MSTeamsToolkit",
    "zoom": "parrot_tools.zoomtoolkit.ZoomUsToolkit",
    "company_info": "parrot_tools.company_info.tool.CompanyInfoToolkit",
    "troc": "parrot_tools.troc.tool.TROCOperationsToolkit",
    "bestbuy": "parrot_tools.retail.bby.BestBuyToolkit",
    "massive": "parrot_tools.massive.toolkit.MassiveToolkit",
    "workday": "parrot_tools.workday.tool.WorkdayToolkit",

    # --- Individual Tools (Batch 1 — simple tools) ---
    "ddg_search": "parrot_tools.ddgsearch.DdgSearchTool",
    "google_voice": "parrot_tools.gvoice.GoogleVoiceTool",
    "bing_search": "parrot_tools.bingsearch.BingSearchTool",
    "serpapi": "parrot_tools.serpapi.SerpApiSearchTool",
    "arxiv": "parrot_tools.arxiv_tool.ArxivTool",
    "openweather": "parrot_tools.openweather.OpenWeatherTool",
    "think": "parrot_tools.think.ThinkTool",
    "math": "parrot_tools.math.MathTool",
    "textfile": "parrot_tools.textfile.TextFileTool",
    "file_reader": "parrot_tools.file_reader.FileReaderTool",
    "chart": "parrot_tools.chart.ChartTool",
    "dftohtml": "parrot_tools.dftohtml.DfToHtmlTool",
    "notification": "parrot_tools.notification.NotificationTool",
    "metadata": "parrot_tools.metadata.MetadataTool",
    "doc_converter": "parrot_tools.doc_converter.DocumentConverterTool",
    "webapp_generator": "parrot_tools.webapp_tool.WebAppGeneratorTool",
    "employees": "parrot_tools.employees.EmployeesTool",
    "powerbi_query": "parrot_tools.powerbi.PowerBIQueryTool",
    "powerbi_table_info": "parrot_tools.powerbi.PowerBITableInfoTool",
    "pdf_print": "parrot_tools.pdfprint.PDFPrintTool",
    "sandbox": "parrot_tools.sandboxtool.SandboxTool",
    "quick_eda": "parrot_tools.quickeda.QuickEdaTool",
    "eda_report": "parrot_tools.edareport.EdaReportTool",
    "calculator": "parrot_tools.calculator.tool.CalculatorTool",
    "file_manager": "parrot_tools.file.tool.FileManagerTool",
    "shell": "parrot_tools.shell_tool.tool.ShellTool",
    "system_health": "parrot_tools.system_health.tool.SystemHealthTool",
    # googlesearch/googlesitesearch/googlelocation/googleroutes are re-exports
    # from the google/ directory — will be added when google/ is migrated (Batch 2)
    "csv_export": "parrot_tools.csv_export.CSVExportTool",
    "excel": "parrot_tools.excel.ExcelTool",
    "msword": "parrot_tools.msword.MSWordTool",
    "word_to_markdown": "parrot_tools.msword.WordToMarkdownTool",
    "powerpoint": "parrot_tools.powerpoint.PowerPointTool",
    "python_pandas": "parrot_tools.pythonpandas.PythonPandasTool",
}
