"""
AI-Parrot Tools & Toolkits package.

TOOL_REGISTRY maps tool names to their dotted import paths.
This enables lazy discovery without importing any tool modules at startup.

Auto-generated by: scripts/generate_tool_registry.py
Manual additions are also supported — the script preserves manual entries.
"""

TOOL_REGISTRY: dict[str, str] = {}
