#!/usr/bin/env python3
"""Offline PageIndex builder for the Odoo documentation PDFs.

Builds one PageIndex tree per Odoo version (``odoo_16``, ``odoo_18``,
``odoo_19``) from the PDFs generated by ``fetch_odoo_docs.sh``.  The trees
are persisted to ``agents/odoo_agent/documentation/`` and consumed at runtime
by the OdooAgent's ``PageIndexToolkit``.

Execution model:
    This is a one-time / periodic offline job — NEVER run on the request
    path.  Call it whenever the Odoo documentation PDFs are refreshed.

Prerequisites:
    - Run ``scripts/odoo_agent/fetch_odoo_docs.sh`` first to generate the PDFs.
    - Set ``GOOGLE_API_KEY`` (or ``GEMINI_API_KEY``) in the environment.
    - Activate the virtual environment: ``source .venv/bin/activate``

Usage:
    # From the repository root
    python scripts/odoo_agent/build_odoo_pageindex.py

    # Force rebuild a single version
    python scripts/odoo_agent/build_odoo_pageindex.py --versions odoo_18 --force

    # Use a different storage directory
    python scripts/odoo_agent/build_odoo_pageindex.py --storage-dir /data/odoo_docs

Options:
    --versions    Comma-separated tree names to build (default: odoo_16,odoo_18,odoo_19)
    --storage-dir Output directory (default: agents/odoo_agent/documentation)
    --force       Rebuild even if the tree already exists in the storage directory
    --model       LLM model for the PageIndexLLMAdapter (default: gemini-2.0-flash-lite)
    --dry-run     Print what would be built without actually ingesting
"""
from __future__ import annotations

import argparse
import asyncio
import logging
import sys
from pathlib import Path

from parrot.clients.google import GoogleGenAIClient
from parrot.knowledge.pageindex import PageIndexLLMAdapter, PageIndexToolkit

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger(__name__)

# Repository root is two levels up from this script
_SCRIPT_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPT_DIR.parent.parent

# Default values
DEFAULT_STORAGE_DIR = str(_REPO_ROOT / "agents" / "odoo_agent" / "documentation")
DEFAULT_MODEL = "gemini-2.0-flash-lite"

# Mapping: tree_name → version directory under the storage dir
VERSION_MAP: dict[str, str] = {
    "odoo_16": "16.0",
    "odoo_18": "18.0",
    "odoo_19": "19.0",
}


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments.

    Args:
        argv: Override sys.argv (used in tests).

    Returns:
        Parsed namespace.
    """
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--versions",
        default=",".join(VERSION_MAP.keys()),
        help="Comma-separated tree names to build (default: all three versions)",
    )
    parser.add_argument(
        "--storage-dir",
        default=DEFAULT_STORAGE_DIR,
        help="PageIndex storage directory (default: agents/odoo_agent/documentation)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Rebuild even if the tree already exists",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"LLM model for PageIndexLLMAdapter (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be built without actually ingesting PDFs",
    )
    return parser.parse_args(argv)


def _find_pdf(version_dir: Path) -> Path | None:
    """Find the first PDF file in a version directory.

    Args:
        version_dir: Directory to search (e.g. documentation/16.0/).

    Returns:
        Path to the PDF, or None if no PDF is found.
    """
    if not version_dir.is_dir():
        return None
    pdfs = sorted(version_dir.glob("*.pdf"))
    return pdfs[0] if pdfs else None


async def build_pageindex(
    storage_dir: str,
    versions: list[str],
    model: str = DEFAULT_MODEL,
    force: bool = False,
    dry_run: bool = False,
) -> dict[str, str]:
    """Build the Odoo documentation PageIndex.

    Creates one tree per requested Odoo version under ``storage_dir``.
    Idempotent: existing trees are skipped unless ``force=True``.

    Args:
        storage_dir: Directory to persist the PageIndex trees.
        versions: List of tree names to build (e.g. ``["odoo_16", "odoo_18"]``).
        model: LLM model string for the adapter.
        force: When True, rebuild even if the tree exists.
        dry_run: When True, skip actual PDF ingestion.

    Returns:
        Mapping of tree_name → outcome ("built", "skipped", "no_pdf", "dry_run").
    """
    storage_path = Path(storage_dir)
    storage_path.mkdir(parents=True, exist_ok=True)

    # Build the LLM adapter (lightweight model for summaries)
    client = GoogleGenAIClient(model=model)
    adapter = PageIndexLLMAdapter(client=client, model=model)

    # Initialise the toolkit against the storage directory
    toolkit = PageIndexToolkit(
        adapter=adapter,
        storage_dir=str(storage_path),
    )

    # Discover which trees already exist
    existing_trees: list[str] = await toolkit.list_trees()
    logger.info("Existing trees: %s", existing_trees)

    outcomes: dict[str, str] = {}

    for tree_name in versions:
        if tree_name not in VERSION_MAP:
            logger.warning(
                "Unknown version key %r — not in VERSION_MAP. Skipping.", tree_name
            )
            outcomes[tree_name] = "unknown"
            continue

        ver = VERSION_MAP[tree_name]
        version_dir = storage_path / ver
        pdf_path = _find_pdf(version_dir)

        if pdf_path is None:
            logger.warning(
                "[%s] No PDF found in %s — run fetch_odoo_docs.sh first.",
                tree_name,
                version_dir,
            )
            outcomes[tree_name] = "no_pdf"
            continue

        if tree_name in existing_trees and not force:
            logger.info(
                "[%s] Tree already exists — skipping (use --force to rebuild).",
                tree_name,
            )
            outcomes[tree_name] = "skipped"
            continue

        if dry_run:
            logger.info("[%s] DRY RUN — would ingest %s", tree_name, pdf_path)
            outcomes[tree_name] = "dry_run"
            continue

        # Delete existing tree if force is requested
        if tree_name in existing_trees and force:
            logger.info("[%s] --force: deleting existing tree before rebuild.", tree_name)
            await toolkit.delete_tree(tree_name)
            existing_trees = await toolkit.list_trees()

        # Create a new empty tree, then import the PDF
        logger.info("[%s] Creating tree (storage: %s)", tree_name, storage_path)
        await toolkit.create_tree(tree_name, doc_name=f"Odoo {ver} Documentation")

        logger.info("[%s] Importing PDF: %s", tree_name, pdf_path)
        result = await toolkit.import_pdf(
            tree_name=tree_name,
            pdf_path=str(pdf_path),
            with_summaries=True,
            with_doc_description=True,
        )
        node_count = len(result.get("new_node_ids", []))
        logger.info(
            "[%s] Import complete — %d nodes created.", tree_name, node_count
        )
        outcomes[tree_name] = "built"

    return outcomes


def main(argv: list[str] | None = None) -> int:
    """Entry point for the offline PageIndex builder.

    Args:
        argv: Override sys.argv (used in tests).

    Returns:
        Exit code (0 for success, 1 for any failure).
    """
    args = _parse_args(argv)
    versions = [v.strip() for v in args.versions.split(",") if v.strip()]

    logger.info(
        "Building Odoo PageIndex: versions=%s storage_dir=%s force=%s dry_run=%s",
        versions,
        args.storage_dir,
        args.force,
        args.dry_run,
    )

    outcomes = asyncio.run(
        build_pageindex(
            storage_dir=args.storage_dir,
            versions=versions,
            model=args.model,
            force=args.force,
            dry_run=args.dry_run,
        )
    )

    logger.info("Outcomes: %s", outcomes)

    failures = [k for k, v in outcomes.items() if v not in ("built", "skipped", "dry_run")]
    if failures:
        logger.error("Failed / missing PDFs for: %s", failures)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
