"""$agent_name agent — generated by parrot setup."""
import logging
from parrot.bots import Agent


logger = logging.getLogger(__name__)


class $class_name(Agent):
    """$agent_name.

    Generated by parrot setup. Customize this class to add tools,
    system prompts, and other configuration.
    """

    agent_id: str = "$agent_id"
    agent_name: str = "$agent_name"

    def __init__(self, **kwargs) -> None:
        """Initialize $agent_name with the configured LLM."""
        super().__init__(
            name="$agent_name",
            agent_id="$agent_id",
            llm="$llm_string",
            **kwargs,
        )
