"""Application entry point — generated by parrot setup."""
from parrot.manager import BotManager
from parrot.conf import STATIC_DIR
from parrot.handlers import AppHandler
from $agent_module import $class_name


class Main(AppHandler):
    """Main application handler.

    Add additional bot registrations and routes in configure().
    """

    app_name: str = "Parrot"
    enable_static: bool = True
    staticdir: str = STATIC_DIR

    def configure(self) -> None:
        """Configure bots and API routes."""
        self.bot_manager = BotManager()
        self.bot_manager.register($class_name())
        self.bot_manager.setup(self.app)
