#!/usr/bin/env python3
"""Run script — generated by parrot setup."""
from navigator import Application
from app import Main

app = Application(Main, enable_jinja2=True)

if __name__ == "__main__":
    app.run()
