"""
AI-Parrot Document Loaders package.

LOADER_REGISTRY maps loader names to their dotted import paths.
This enables lazy discovery without importing any loader modules at startup.

Auto-generated by: scripts/generate_loader_registry.py
"""

LOADER_REGISTRY: dict[str, str] = {}
