"""Weekly and monthly security report summarizers.

Deterministic Python math (severity totals + finding set-diffs) combined
with a single LLM call for the executive paragraph.

Implements Spec §3 Module 8.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field

from parrot.storage.security_reports import (
    EmbeddedFinding,
    ReportRef,
    SeverityBreakdown,
)


# ---------------------------------------------------------------------------
# Public Pydantic models
# ---------------------------------------------------------------------------


class WeeklySummary(BaseModel):
    """A week-scoped security posture summary for one (provider, framework) pair.

    Attributes:
        framework: Compliance framework (e.g., ``"HIPAA"``).
        provider: Cloud / infra provider (e.g., ``"aws"``, ``"container"``).
        period_start: Earliest ``produced_at`` timestamp among source scans.
        period_end: Latest ``produced_at`` timestamp among source scans.
        severity_totals: Element-wise sum of severity counts across all scans.
        new_findings: Findings present in current scans but NOT in the
            previous week's ``persistent_findings``.
        resolved_findings: Findings present in the previous week's
            ``persistent_findings`` but NOT in current scans.
        persistent_findings: Findings present in BOTH current scans and the
            previous week's ``persistent_findings``.
        executive_paragraph: 3–5 sentence narrative generated by the LLM.
        source_report_ids: UUIDs of the ``ReportRef`` scan reports consumed.
    """

    framework: str
    provider: str
    period_start: datetime
    period_end: datetime
    severity_totals: SeverityBreakdown
    new_findings: list[EmbeddedFinding] = Field(default_factory=list)
    resolved_findings: list[EmbeddedFinding] = Field(default_factory=list)
    persistent_findings: list[EmbeddedFinding] = Field(default_factory=list)
    executive_paragraph: str
    source_report_ids: list[UUID] = Field(default_factory=list)


class MonthlySummary(BaseModel):
    """A month-scoped security posture summary for one (provider, framework) pair.

    Produced by consuming the four weekly summaries for the month.  The diff
    math operates on weekly ``persistent_findings`` sets (findings that
    persisted across the whole week are more signal-worthy at monthly scope).

    Attributes:
        framework: Compliance framework (e.g., ``"HIPAA"``).
        provider: Cloud / infra provider.
        period_start: Earliest ``period_start`` among source weekly summaries.
        period_end: Latest ``period_end`` among source weekly summaries.
        severity_totals: Sum of ``severity_totals`` across weekly summaries.
        persistent_findings: Findings present across ALL weekly summaries.
        executive_paragraph: 3–5 sentence monthly narrative from the LLM.
        source_report_ids: UUIDs of the ``ReportRef`` weekly_summary reports
            consumed (typically 4, one per week).
    """

    framework: str
    provider: str
    period_start: datetime
    period_end: datetime
    severity_totals: SeverityBreakdown
    persistent_findings: list[EmbeddedFinding] = Field(default_factory=list)
    executive_paragraph: str
    source_report_ids: list[UUID] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Internal LLM schema
# ---------------------------------------------------------------------------


class _Executive(BaseModel):
    """Minimal schema for the LLM executive-paragraph call."""

    paragraph: str = Field(..., description="3-5 sentence executive summary paragraph.")


# ---------------------------------------------------------------------------
# Helper: deterministic finding sort
# ---------------------------------------------------------------------------

_SEV_RANK: dict[str, int] = {
    "CRITICAL": 0,
    "HIGH": 1,
    "MEDIUM": 2,
    "LOW": 3,
    "INFORMATIONAL": 4,
}


def _sort_findings(findings: list[EmbeddedFinding]) -> list[EmbeddedFinding]:
    """Sort findings deterministically: severity rank then finding_id."""
    return sorted(
        findings,
        key=lambda f: (_SEV_RANK.get(f.severity.upper(), 5), f.finding_id),
    )


# ---------------------------------------------------------------------------
# WeeklySecuritySummarizer
# ---------------------------------------------------------------------------


class WeeklySecuritySummarizer:
    """Produces a ``WeeklySummary`` from a list of scan ``ReportRef``s.

    All severity arithmetic is deterministic Python — the LLM is invoked
    EXACTLY ONCE per ``build()`` call, solely to generate the
    ``executive_paragraph``.

    Args:
        llm_client: Any LLM client that exposes an async ``ask()`` method
            accepting ``prompt: str`` and ``structured_output: type``, and
            returns an object with a ``structured_output`` attribute containing
            the parsed Pydantic model.  The ``GoogleGenAIClient`` satisfies
            this contract.
    """

    def __init__(self, llm_client: Any) -> None:
        self._llm = llm_client
        self._logger = logging.getLogger(__name__)

    async def build(
        self,
        scans: list[ReportRef],
        framework: str,
        provider: str,
        previous_summary_data: WeeklySummary | None = None,
    ) -> WeeklySummary:
        """Build a ``WeeklySummary`` for the given scan refs.

        Args:
            scans: List of ``ReportRef`` objects with ``report_kind=SCAN``.
                May be empty (produces zeroed-out severity totals).
            framework: Compliance framework label (e.g., ``"HIPAA"``).
            provider: Cloud provider label (e.g., ``"aws"``).
            previous_summary_data: Deserialized ``WeeklySummary`` from the
                previous period, used for diff math.  Pass ``None`` on first
                run (all current findings treated as new).

        Returns:
            ``WeeklySummary`` with deterministic math + LLM executive paragraph.
        """
        now = datetime.now(timezone.utc)
        period_start = min((s.produced_at for s in scans), default=now)
        period_end = max((s.produced_at for s in scans), default=now)

        # 1. Deterministic severity totals: element-wise sum across scans.
        totals = SeverityBreakdown(
            critical=sum(s.severity_summary.critical for s in scans),
            high=sum(s.severity_summary.high for s in scans),
            medium=sum(s.severity_summary.medium for s in scans),
            low=sum(s.severity_summary.low for s in scans),
            informational=sum(s.severity_summary.informational for s in scans),
        )

        # 2. Set-op finding diffs on finding_id.
        #    current_findings: id → EmbeddedFinding (latest scan wins on dupe id)
        current_findings: dict[str, EmbeddedFinding] = {
            f.finding_id: f
            for s in scans
            for f in s.top_findings
        }
        previous_findings: dict[str, EmbeddedFinding] = {
            f.finding_id: f
            for f in (previous_summary_data.persistent_findings if previous_summary_data else [])
        }

        current_ids = set(current_findings.keys())
        previous_ids = set(previous_findings.keys())

        new_ids = current_ids - previous_ids
        resolved_ids = previous_ids - current_ids
        persistent_ids = current_ids & previous_ids

        new_findings = _sort_findings([current_findings[fid] for fid in new_ids])
        resolved_findings = _sort_findings([previous_findings[fid] for fid in resolved_ids])
        persistent_findings = _sort_findings([current_findings[fid] for fid in persistent_ids])

        # 3. Single LLM call — only for the executive paragraph.
        exec_result = await self._call_llm_for_exec(
            framework=framework,
            provider=provider,
            totals=totals,
            new=new_findings,
            resolved=resolved_findings,
            persistent=persistent_findings,
        )

        return WeeklySummary(
            framework=framework,
            provider=provider,
            period_start=period_start,
            period_end=period_end,
            severity_totals=totals,
            new_findings=new_findings,
            resolved_findings=resolved_findings,
            persistent_findings=persistent_findings,
            executive_paragraph=exec_result.paragraph,
            source_report_ids=[s.report_id for s in scans],
        )

    async def _call_llm_for_exec(
        self,
        *,
        framework: str,
        provider: str,
        totals: SeverityBreakdown,
        new: list[EmbeddedFinding],
        resolved: list[EmbeddedFinding],
        persistent: list[EmbeddedFinding],
    ) -> _Executive:
        """Compose prompt and call the LLM for the executive paragraph.

        Args:
            framework: Compliance framework label.
            provider: Cloud provider label.
            totals: Aggregated severity counts.
            new: New findings (not seen in previous period).
            resolved: Resolved findings (seen in previous period, gone now).
            persistent: Persistent findings (present in both periods).

        Returns:
            ``_Executive`` Pydantic model with the generated paragraph.
        """
        def _fmt_findings(findings: list[EmbeddedFinding], label: str) -> str:
            if not findings:
                return f"{label}: none"
            items = "; ".join(
                f"[{f.severity}] {f.title}" for f in findings[:5]
            )
            suffix = f" (+ {len(findings) - 5} more)" if len(findings) > 5 else ""
            return f"{label}: {items}{suffix}"

        prompt = (
            f"Write a 3-5 sentence executive security summary for the weekly report.\n\n"
            f"Framework: {framework}\n"
            f"Provider: {provider}\n"
            f"Severity totals — "
            f"CRITICAL: {totals.critical}, HIGH: {totals.high}, "
            f"MEDIUM: {totals.medium}, LOW: {totals.low}\n"
            f"{_fmt_findings(new, 'New findings')}\n"
            f"{_fmt_findings(resolved, 'Resolved findings')}\n"
            f"{_fmt_findings(persistent, 'Persistent findings')}\n\n"
            f"Return only the executive paragraph."
        )
        self._logger.debug(
            "Calling LLM for executive paragraph (framework=%s, provider=%s)", framework, provider
        )
        response = await self._llm.ask(prompt, structured_output=_Executive, stateless=True)
        return response.structured_output


# ---------------------------------------------------------------------------
# MonthlySecuritySummarizer
# ---------------------------------------------------------------------------


class MonthlySecuritySummarizer:
    """Produces a ``MonthlySummary`` from a list of weekly ``WeeklySummary`` objects.

    Diff math operates on the ``persistent_findings`` sets of each weekly
    summary.  The LLM is invoked EXACTLY ONCE per ``build()`` call, solely
    for the ``executive_paragraph``.

    Args:
        llm_client: Any LLM client satisfying the same contract as
            ``WeeklySecuritySummarizer``.
    """

    def __init__(self, llm_client: Any) -> None:
        self._llm = llm_client
        self._logger = logging.getLogger(__name__)

    async def build(
        self,
        weekly_summaries: list[WeeklySummary],
        framework: str,
        provider: str,
    ) -> MonthlySummary:
        """Build a ``MonthlySummary`` from a list of weekly summaries.

        Args:
            weekly_summaries: List of ``WeeklySummary`` objects for the month
                (typically 4, one per week).  May be empty.
            framework: Compliance framework label (e.g., ``"HIPAA"``).
            provider: Cloud provider label (e.g., ``"aws"``).

        Returns:
            ``MonthlySummary`` with deterministic math + LLM executive paragraph.
        """
        now = datetime.now(timezone.utc)
        period_start = min((w.period_start for w in weekly_summaries), default=now)
        period_end = max((w.period_end for w in weekly_summaries), default=now)

        # 1. Deterministic severity totals: sum across weekly summaries.
        totals = SeverityBreakdown(
            critical=sum(w.severity_totals.critical for w in weekly_summaries),
            high=sum(w.severity_totals.high for w in weekly_summaries),
            medium=sum(w.severity_totals.medium for w in weekly_summaries),
            low=sum(w.severity_totals.low for w in weekly_summaries),
            informational=sum(w.severity_totals.informational for w in weekly_summaries),
        )

        # 2. Monthly persistence: findings present in ALL weeks' persistent sets.
        #    On zero or one week, treat all findings as persistent.
        if not weekly_summaries:
            persistent_findings: list[EmbeddedFinding] = []
        elif len(weekly_summaries) == 1:
            persistent_findings = list(weekly_summaries[0].persistent_findings)
        else:
            # Intersection across all weekly persistent_finding_ids.
            weekly_id_sets = [
                {f.finding_id for f in w.persistent_findings} for w in weekly_summaries
            ]
            persistent_ids = weekly_id_sets[0].intersection(*weekly_id_sets[1:])
            # Pick canonical EmbeddedFinding from the latest week that has it.
            canonical: dict[str, EmbeddedFinding] = {}
            for w in weekly_summaries:
                for f in w.persistent_findings:
                    if f.finding_id in persistent_ids:
                        canonical[f.finding_id] = f  # last week wins
            persistent_findings = _sort_findings(list(canonical.values()))

        # Collect source_report_ids: UUIDs from all weeks' source_report_ids.
        source_report_ids: list[UUID] = [
            rid for w in weekly_summaries for rid in w.source_report_ids
        ]

        # 3. Single LLM call — only for the executive paragraph.
        exec_result = await self._call_llm_for_exec(
            framework=framework,
            provider=provider,
            totals=totals,
            persistent=persistent_findings,
            n_weeks=len(weekly_summaries),
        )

        return MonthlySummary(
            framework=framework,
            provider=provider,
            period_start=period_start,
            period_end=period_end,
            severity_totals=totals,
            persistent_findings=persistent_findings,
            executive_paragraph=exec_result.paragraph,
            source_report_ids=source_report_ids,
        )

    async def _call_llm_for_exec(
        self,
        *,
        framework: str,
        provider: str,
        totals: SeverityBreakdown,
        persistent: list[EmbeddedFinding],
        n_weeks: int,
    ) -> _Executive:
        """Compose monthly prompt and call the LLM for the executive paragraph.

        Args:
            framework: Compliance framework label.
            provider: Cloud provider label.
            totals: Aggregated monthly severity counts.
            persistent: Findings that persisted across all weekly summaries.
            n_weeks: Number of weekly summaries consumed.

        Returns:
            ``_Executive`` Pydantic model with the generated paragraph.
        """
        def _fmt(findings: list[EmbeddedFinding]) -> str:
            if not findings:
                return "none"
            items = "; ".join(f"[{f.severity}] {f.title}" for f in findings[:5])
            suffix = f" (+ {len(findings) - 5} more)" if len(findings) > 5 else ""
            return f"{items}{suffix}"

        prompt = (
            f"Write a 3-5 sentence executive monthly security summary.\n\n"
            f"Framework: {framework}\n"
            f"Provider: {provider}\n"
            f"Weeks covered: {n_weeks}\n"
            f"Monthly severity totals — "
            f"CRITICAL: {totals.critical}, HIGH: {totals.high}, "
            f"MEDIUM: {totals.medium}, LOW: {totals.low}\n"
            f"Persistent findings (present all month): {_fmt(persistent)}\n\n"
            f"Return only the monthly executive paragraph."
        )
        self._logger.debug(
            "Calling LLM for monthly executive paragraph (framework=%s, provider=%s)",
            framework,
            provider,
        )
        response = await self._llm.ask(prompt, structured_output=_Executive, stateless=True)
        return response.structured_output
