from enum import Enum

class AlphaVantageFunctions(str, Enum):
    """
    Enum of available functions for the Alpha Vantage MCP server.
    These function names should be passed as the `function` argument to the `TOOL_CALL` tool.
    """
    
    # Core Stock APIs
    TIME_SERIES_INTRADAY = "TIME_SERIES_INTRADAY"
    TIME_SERIES_DAILY = "TIME_SERIES_DAILY"
    TIME_SERIES_DAILY_ADJUSTED = "TIME_SERIES_DAILY_ADJUSTED"
    TIME_SERIES_WEEKLY = "TIME_SERIES_WEEKLY"
    TIME_SERIES_WEEKLY_ADJUSTED = "TIME_SERIES_WEEKLY_ADJUSTED"
    TIME_SERIES_MONTHLY = "TIME_SERIES_MONTHLY"
    TIME_SERIES_MONTHLY_ADJUSTED = "TIME_SERIES_MONTHLY_ADJUSTED"
    GLOBAL_QUOTE = "GLOBAL_QUOTE"
    REALTIME_BULK_QUOTES = "REALTIME_BULK_QUOTES"
    SYMBOL_SEARCH = "SYMBOL_SEARCH"
    MARKET_STATUS = "MARKET_STATUS"
    
    # Options Data APIs
    REALTIME_OPTIONS = "REALTIME_OPTIONS"
    HISTORICAL_OPTIONS = "HISTORICAL_OPTIONS"
    
    # Alpha Intelligence
    NEWS_SENTIMENT = "NEWS_SENTIMENT"
    EARNINGS_CALL_TRANSCRIPT = "EARNINGS_CALL_TRANSCRIPT"
    TOP_GAINERS_LOSERS = "TOP_GAINERS_LOSERS"
    INSIDER_TRANSACTIONS = "INSIDER_TRANSACTIONS"
    ANALYTICS_FIXED_WINDOW = "ANALYTICS_FIXED_WINDOW"
    ANALYTICS_SLIDING_WINDOW = "ANALYTICS_SLIDING_WINDOW"
    
    # Fundamental Data
    COMPANY_OVERVIEW = "COMPANY_OVERVIEW"
    INCOME_STATEMENT = "INCOME_STATEMENT"
    BALANCE_SHEET = "BALANCE_SHEET"
    CASH_FLOW = "CASH_FLOW"
    EARNINGS = "EARNINGS"
    LISTING_STATUS = "LISTING_STATUS"
    EARNINGS_CALENDAR = "EARNINGS_CALENDAR"
    IPO_CALENDAR = "IPO_CALENDAR"
    
    # Forex
    FX_INTRADAY = "FX_INTRADAY"
    FX_DAILY = "FX_DAILY"
    FX_WEEKLY = "FX_WEEKLY"
    FX_MONTHLY = "FX_MONTHLY"
    CURRENCY_EXCHANGE_RATE = "CURRENCY_EXCHANGE_RATE"
    
    # Cryptocurrencies
    DIGITAL_CURRENCY_INTRADAY = "DIGITAL_CURRENCY_INTRADAY"
    DIGITAL_CURRENCY_DAILY = "DIGITAL_CURRENCY_DAILY"
    DIGITAL_CURRENCY_WEEKLY = "DIGITAL_CURRENCY_WEEKLY"
    DIGITAL_CURRENCY_MONTHLY = "DIGITAL_CURRENCY_MONTHLY"
    
    # Commodities
    WTI = "WTI"
    BRENT = "BRENT"
    NATURAL_GAS = "NATURAL_GAS"
    COPPER = "COPPER"
    ALUMINUM = "ALUMINUM"
    WHEAT = "WHEAT"
    CORN = "CORN"
    COTTON = "COTTON"
    SUGAR = "SUGAR"
    COFFEE = "COFFEE"
    GOLD_SILVER_SPOT = "GOLD_SILVER_SPOT"
    GOLD_SILVER_HISTORY = "GOLD_SILVER_HISTORY"
    ALL_COMMODITIES = "ALL_COMMODITIES"
    
    # Economic Indicators
    REAL_GDP = "REAL_GDP"
    REAL_GDP_PER_CAPITA = "REAL_GDP_PER_CAPITA"
    TREASURY_YIELD = "TREASURY_YIELD"
    FEDERAL_FUNDS_RATE = "FEDERAL_FUNDS_RATE"
    CPI = "CPI"
    INFLATION = "INFLATION"
    RETAIL_SALES = "RETAIL_SALES"
    DURABLES = "DURABLES"
    UNEMPLOYMENT = "UNEMPLOYMENT"
    NONFARM_PAYROLL = "NONFARM_PAYROLL"
    
    # Technical Indicators
    SMA = "SMA"
    EMA = "EMA"
    WMA = "WMA"
    DEMA = "DEMA"
    TEMA = "TEMA"
    TRIMA = "TRIMA"
    KAMA = "KAMA"
    MAMA = "MAMA"
    VWAP = "VWAP"
    T3 = "T3"
    MACD = "MACD"
    MACDEXT = "MACDEXT"
    STOCH = "STOCH"
    STOCHF = "STOCHF"
    RSI = "RSI"
    STOCHRSI = "STOCHRSI"
    WILLR = "WILLR"
    ADX = "ADX"
    ADXR = "ADXR"
    APO = "APO"
    PPO = "PPO"
    MOM = "MOM"
    BOP = "BOP"
    CCI = "CCI"
    CMO = "CMO"
    ROC = "ROC"
    ROCR = "ROCR"
    AROON = "AROON"
    AROONOSC = "AROONOSC"
    MFI = "MFI"
    TRIX = "TRIX"
    ULTOSC = "ULTOSC"
    DX = "DX"
    MINUS_DI = "MINUS_DI"
    PLUS_DI = "PLUS_DI"
    MINUS_DM = "MINUS_DM"
    PLUS_DM = "PLUS_DM"
    BBANDS = "BBANDS"
    MIDPOINT = "MIDPOINT"
    MIDPRICE = "MIDPRICE"
    SAR = "SAR"
    TRANGE = "TRANGE"
    ATR = "ATR"
    NATR = "NATR"
    AD = "AD"
    ADOSC = "ADOSC"
    OBV = "OBV"
    HT_TRENDLINE = "HT_TRENDLINE"
    HT_SINE = "HT_SINE"
    HT_TRENDMODE = "HT_TRENDMODE"
    HT_DCPERIOD = "HT_DCPERIOD"
    HT_DCPHASE = "HT_DCPHASE"
    
    # Ping
    PING = "PING"
    ADD_TWO_NUMBERS = "ADD_TWO_NUMBERS"

    @classmethod
    def list_functions(cls) -> list[str]:
        return [f.value for f in cls]
