"""
Navigator context provider using PageIndex (vectorless, LLM-driven RAG).

Replaces the previous LocalKB + FAISS approach with PageIndex tree-search:
- Layer 1: tree_context (node summaries) injected into CONFIGURE phase prompt
- Layer 2: retriever.retrieve(query) for on-demand detailed context per request
- Layer 3: get_widget_schema() tool for exact DB lookups (unchanged)

PageIndex advantages over embedding-based RAG:
- No FAISS/vector DB required
- LLM reasons over document structure (hierarchy-aware)
- Works with any LLM (uses gemini-flash-lite by default)
- Transparent: thinking field explains retrieval decisions
- Markdown headers map naturally to tree nodes
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Optional

from parrot.bots.prompts.layers import PromptLayer, LayerPriority, RenderPhase
from parrot.pageindex import PageIndexLLMAdapter, PageIndexRetriever, md_to_tree
from parrot.pageindex.utils import write_node_id

logger = logging.getLogger("parrot.navigator")

# KB directory with markdown docs
KB_DIR = Path(__file__).resolve().parent.parent.parent.parent.parent / "agents" / "navigator" / "kb"
# Pre-built tree cache
TREE_CACHE_FILE = KB_DIR / ".pageindex_tree.json"


# ── PROMPT LAYERS ──────────────────────────────────────────────

_WIDGET_INSTRUCTIONS = """
IMPORTANT: When creating widgets, always:
1. Use get_widget_schema(widget_type_id) to get the exact JSON structure
2. Use find_widget_templates(widget_type_id) to find a reusable template
3. Reference a template_id and only override fields that differ
4. Set widgetcat_id=3 (generic) unless specifically needed otherwise
5. Include grid_position ({h, w, x, y}) to place the widget in the dashboard
6. Use search_widget_docs(query) for detailed configuration docs"""


def _build_tree_context_layer(tree_context: str) -> PromptLayer:
    """Build a PromptLayer with pre-resolved tree context content.

    The content is inlined into the template so no $variable substitution
    is needed during the bot's configure() phase.
    """
    return PromptLayer(
        name="navigator_tree_context",
        priority=LayerPriority.KNOWLEDGE - 5,
        phase=RenderPhase.CONFIGURE,
        template=f"""<navigator_knowledge_index>
{tree_context}
{_WIDGET_INSTRUCTIONS}
</navigator_knowledge_index>""",
    )

NAVIGATOR_OPERATIONS_LAYER = PromptLayer(
    name="navigator_operations",
    priority=LayerPriority.PRE_INSTRUCTIONS + 1,
    phase=RenderPhase.CONFIGURE,
    template="""<navigator_rules>
You manage the Navigator platform. Key rules:

## Access Chain
User → user_groups → Group → program_groups → Program → Modules → Dashboards → Widgets
Only create/edit entities the current user has access to.

## Entity Hierarchy
Program (auth.programs) → Module (navigator.modules) → Dashboard (navigator.dashboards) → Widget (navigator.widgets)

## Creation Flow
1. Program: create_program (superuser only) → assigns to clients + groups
2. Module: create_module → set attributes with menu_type parent/child for hierarchy
3. Dashboard: create_dashboard → type '3' (standard), explorer 'v3'
4. Widget: create_widget → reference template_id, set query_slug, grid_position

## Module Hierarchy
Parent: attributes.menu_type = "parent", parent_img, parent_menu
Child: attributes.menu_type = "child", menu_id = [parent_module_ids], layout_style = "min"

## Dashboard Layout
widget_location in attributes: {"Widget Title": {"h": height, "w": width(max12), "x": col, "y": row}}

## Soft Delete
Always use active=false / enabled=false. Never DELETE records.

## Immutable Fields
program_slug never changes after creation. Slugs auto-generated by triggers.
</navigator_rules>""",
)


# ── PAGEINDEX MANAGER ──────────────────────────────────────────

class NavigatorPageIndex:
    """Manages the PageIndex tree for Navigator knowledge base.

    Indexes all markdown files in agents/navigator/kb/ into a single
    hierarchical tree. Provides:
    - tree_context: compact node summaries for system prompt (Layer 1)
    - retrieve(query): detailed context for a specific query (Layer 2)

    Usage:
        page_index = NavigatorPageIndex()
        await page_index.build(adapter)  # Index all KB docs

        # Layer 1: compact tree for prompt
        tree_context = page_index.get_tree_context()

        # Layer 2: detailed retrieval per query
        context = await page_index.retrieve("How to configure api-card?")
    """

    def __init__(self, kb_dir: Path = KB_DIR, cache_file: Path = TREE_CACHE_FILE):
        self.kb_dir = kb_dir
        self.cache_file = cache_file
        self._tree: Optional[dict] = None
        self._retriever: Optional[PageIndexRetriever] = None
        self._built = False

    async def build(self, adapter: PageIndexLLMAdapter) -> None:
        """Build or load the PageIndex tree from KB markdown files."""
        # Try loading from cache first
        if self.cache_file.exists():
            try:
                self._tree = json.loads(self.cache_file.read_text(encoding="utf-8"))
                self._retriever = PageIndexRetriever(
                    tree=self._tree,
                    adapter=adapter,
                    expert_knowledge=(
                        "This knowledge base covers the Navigator platform: "
                        "widget types and their JSON configurations, "
                        "programs, modules, dashboards, and operational rules."
                    ),
                )
                self._built = True
                logger.info(
                    "NavigatorPageIndex loaded from cache: %s nodes",
                    len(self._tree.get("structure", []))
                )
                return
            except Exception as e:
                logger.warning("Cache load failed, rebuilding: %s", e)

        # Build from markdown files
        md_files = sorted(self.kb_dir.glob("*.md"))
        if not md_files:
            logger.warning("No markdown files found in %s", self.kb_dir)
            return

        merged_structure: list[dict[str, Any]] = []
        for md_file in md_files:
            content = md_file.read_text(encoding="utf-8")
            doc_tree = await md_to_tree(
                md_text=content,
                adapter=adapter,
                doc_name=md_file.stem,
                options={
                    "if_add_node_summary": "yes",
                    "if_add_node_id": "yes",
                    "if_add_doc_description": "no",
                },
            )
            doc_node = {
                "title": md_file.stem.replace("_", " ").title(),
                "summary": f"Knowledge base document: {md_file.name}",
                "nodes": doc_tree.get("structure", []),
            }
            merged_structure.append(doc_node)
            logger.info("Indexed %s: %d top-level nodes", md_file.name, len(doc_tree.get("structure", [])))

        write_node_id(merged_structure)
        self._tree = {
            "doc_name": "navigator_knowledge_base",
            "doc_description": (
                "Complete knowledge base for the Navigator platform: "
                "widget types catalog (66 types), JSON configurations, "
                "programs, modules, dashboards, and operational rules."
            ),
            "structure": merged_structure,
        }

        # Save cache
        try:
            self.cache_file.write_text(
                json.dumps(self._tree, ensure_ascii=False, indent=2),
                encoding="utf-8"
            )
            logger.info("PageIndex tree cached to %s", self.cache_file)
        except Exception as e:
            logger.warning("Failed to cache tree: %s", e)

        self._retriever = PageIndexRetriever(
            tree=self._tree,
            adapter=adapter,
            expert_knowledge=(
                "This knowledge base covers the Navigator platform: "
                "widget types (api-echarts, api-card, api-pqtable, etc.) "
                "with their exact JSON params/conditions/format_definition structures, "
                "plus programs, modules, dashboards, and operational rules."
            ),
        )
        self._built = True
        logger.info("NavigatorPageIndex built: %d documents, %d top nodes", len(md_files), len(merged_structure))

    def get_tree_context(self) -> str:
        """Get compact tree context for system prompt (Layer 1).

        Returns formatted node IDs + titles + summaries.
        Typically ~2K tokens — fits in system prompt without bloat.
        """
        if not self._retriever:
            return "Navigator knowledge base not loaded. Use search_widget_docs tool."
        return self._retriever.get_tree_context(include_summaries=True)

    async def retrieve(self, query: str) -> dict[str, Any]:
        """Retrieve detailed context for a query (Layer 2).

        Returns thinking (LLM reasoning) + matched content.
        """
        if not self._retriever:
            return {"thinking": "Index not built", "context": "", "node_list": []}
        # Use search() once, then manually extract text from matched nodes
        # to avoid the double LLM call that retrieve() would make internally
        search_result = await self._retriever.search(query)
        if not search_result.node_list:
            return {"thinking": search_result.thinking, "context": "", "node_list": []}
        # Extract content from matched nodes directly
        from parrot.pageindex.utils import find_node_by_id
        context_parts = []
        for node_id in search_result.node_list:
            node = find_node_by_id(self._retriever.structure, node_id)
            if not node:
                continue
            title = node.get("title", "Section")
            text = node.get("text") or node.get("summary") or node.get("prefix_summary") or ""
            if text:
                context_parts.append(f"## {title}\n{text}")
        return {
            "thinking": search_result.thinking,
            "node_list": search_result.node_list,
            "context": "\n\n".join(context_parts),
        }

    @property
    def is_built(self) -> bool:
        return self._built

    def get_tree_json(self) -> Optional[dict]:
        return self._tree


# ── PUBLIC API ─────────────────────────────────────────────────

def get_navigator_layers(page_index: NavigatorPageIndex = None) -> list[PromptLayer]:
    """Return all custom Navigator prompt layers.

    Args:
        page_index: If provided, includes a tree context layer with
                    pre-resolved node summaries from the PageIndex.

    Usage:
        page_index = NavigatorPageIndex()
        await page_index.build(adapter)

        builder = PromptBuilder.default()
        for layer in get_navigator_layers(page_index):
            builder.add(layer)
    """
    layers = [NAVIGATOR_OPERATIONS_LAYER]
    if page_index and page_index.is_built:
        tree_context = page_index.get_tree_context()
        layers.insert(0, _build_tree_context_layer(tree_context))
    else:
        # Fallback: load compact catalog from disk
        compact_file = KB_DIR / "widget_types_compact.md"
        if compact_file.exists():
            content = compact_file.read_text(encoding="utf-8")
            layers.insert(0, _build_tree_context_layer(content))
    return layers
