#!/usr/bin/env python3
"""Generate frontend implementation documentation for FieldType.REST.

This script reads the Pydantic schemas for ``RestFieldSpec`` and
``RestFieldResult`` and produces a Markdown file at
``docs/frontend/rest-field.md`` describing:

- The JSON-Schema extension (``x-parrot-rest``)
- Upload endpoint contract (URL template, multipart body, headers)
- Response envelope shape
- Error codes
- A worked planogram example

Usage::

    python scripts/gen_frontend_docs.py [--out PATH]

If ``--out`` is not given, the output goes to
``docs/frontend/rest-field.md`` relative to the package root (i.e., the
directory containing this script's parent directory).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Add the package src to sys.path so the script can import without installing
_SCRIPT_DIR = Path(__file__).resolve().parent
_PACKAGE_SRC = _SCRIPT_DIR.parent / "src"
if str(_PACKAGE_SRC) not in sys.path:
    sys.path.insert(0, str(_PACKAGE_SRC))


def _generate(out_path: Path) -> None:
    """Generate and write the frontend REST-field documentation.

    Args:
        out_path: Path where the Markdown output will be written.
    """
    from pydantic import TypeAdapter

    from parrot_formdesigner.core.types import FieldType
    from parrot_formdesigner.services.rest_field_resolver import (
        RestFieldResult,
        RestFieldSpec,
        RemoteRestFieldSpec,
        InternalRestFieldSpec,
        CallbackRestFieldSpec,
    )

    # Pydantic JSON schemas
    spec_adapter = TypeAdapter(RestFieldSpec)
    spec_schema = spec_adapter.json_schema()

    result_schema = RestFieldResult.model_json_schema()

    mode_values = ["remote", "internal", "callback"]

    doc = f"""\
# FieldType.REST — Frontend Implementation Guide

> Auto-generated by `scripts/gen_frontend_docs.py`. Do not edit manually.

## Overview

`FieldType.REST` (value: `"rest"`) is a **REST-driven upload field**.
The user uploads a file (photo, document, etc.); the form runtime forwards
it to a REST endpoint or registered Python callback, and the API response
becomes the field's answer value.

Three modes are supported: **remote**, **internal**, and **callback**.

---

## JSON Schema Extension (`x-parrot-rest`)

When a form is rendered as JSON Schema, REST fields carry an `x-parrot-rest`
extension object:

```json
{{
  "type": "object",
  "format": "rest",
  "properties": {{
    "answer": {{}},
    "blob_ref": {{"type": ["string", "null"]}}
  }},
  "required": ["answer"],
  "x-parrot-rest": {{
    "mode": "<remote|internal|callback>",
    "response_path": "$.field (JSONPath, optional)",
    "display_template": "Jinja2 template (optional)",
    "upload_url_template": "/api/v1/forms/{{form_id}}/fields/{{field_id}}/upload"
  }}
}}
```

### `x-parrot-rest` fields

| Field | Type | Description |
|---|---|---|
| `mode` | string | One of: `remote`, `internal`, `callback` |
| `response_path` | string\\|null | JSONPath expression to extract `answer` from API response |
| `display_template` | string\\|null | Jinja2 template for human-readable display (receives `answer`) |
| `upload_url_template` | string | URL template for the upload POST endpoint |

---

## Modes

### `remote` mode

Sends the upload to an **absolute URL** (external vendor API).

```json
{{
  "mode": "remote",
  "endpoint": "https://api.vendor.example/analyse",
  "http_method": "POST",
  "response_path": "$.score",
  "display_template": "Score: {{{{ answer }}}}"
}}
```

### `internal` mode

Sends the upload to a **relative path on the same server** (must start with `/`).

```json
{{
  "mode": "internal",
  "endpoint": "/internal/ml/classify",
  "http_method": "POST",
  "response_path": "$.category"
}}
```

### `callback` mode

Invokes a **pre-registered Python coroutine** by name.

```json
{{
  "mode": "callback",
  "callback_ref": "planogram_compliance",
  "response_path": "$.compliance_score",
  "display_template": "Compliance: {{{{ (answer * 100) | round }}}}/100"
}}
```

---

## Upload Endpoint Contract

### URL

```
POST /api/v1/forms/{{form_id}}/fields/{{field_id}}/upload
```

### Request

| Element | Value |
|---|---|
| Content-Type | `multipart/form-data` |
| Auth | Bearer token (navigator-auth) |
| Part name | `file` (required) |

#### Optional Headers

| Header | Description |
|---|---|
| `X-Parrot-Prior-Blob-Ref` | URI of previously-uploaded blob to delete after new upload succeeds |
| `X-Parrot-Tenant` | Tenant slug override for callback namespace resolution |

### Response Envelope

```json
{{
  "success": true,
  "answer": <any>,
  "raw_value": <any>,
  "blob_ref": "s3://bucket/path/to/blob",
  "display": "Human-readable string (if display_template configured)",
  "warnings": ["optional warning strings"],
  "error": null
}}
```

On resolver failure (`success: false`), the HTTP status is still **200**:

```json
{{
  "success": false,
  "answer": null,
  "raw_value": null,
  "blob_ref": "s3://bucket/path/to/blob",
  "display": null,
  "warnings": [],
  "error": "callback not found: planogram_compliance"
}}
```

---

## Error Codes

| HTTP Status | Cause |
|---|---|
| 400 | Malformed multipart body or no `file` part |
| 401 | Unauthenticated request |
| 404 | Form or field not found, or field is not `FieldType.REST` |
| 413 | Upload exceeds `field.constraints.max_file_size_bytes` |
| 415 | MIME type not in `field.constraints.allowed_mime_types` |
| 500 | Unexpected server error (resolver contract: known errors → `success=false` at 200) |

---

## Frontend Component Hints

The HTML5 renderer emits the following markup for REST fields:

```html
<div class="parrot-rest-uploader"
     data-field-id="{{field_id}}"
     data-upload-url="/api/v1/forms/{{form_id}}/fields/{{field_id}}/upload">
  <input type="file"
         name="{{field_id}}_file"
         accept="image/jpeg,image/png">
  <input type="hidden" name="{{field_id}}.answer">
  <input type="hidden" name="{{field_id}}.blob_ref">
  <span class="rest-status"></span>
</div>
```

Your `<RestUploader>` component should:

1. Intercept the file input `change` event.
2. POST a `multipart/form-data` request to `data-upload-url`.
3. On success, populate the hidden `answer` and `blob_ref` inputs.
4. On re-upload, send `X-Parrot-Prior-Blob-Ref: <previous blob_ref>`.
5. Display `result.display` (or a spinner/error) in the `.rest-status` element.

---

## Worked Example — Planogram Compliance

Field definition in YAML:

```yaml
field_id: planogram_photo
field_type: rest
label: "Subir foto para planogram compliance"
required: true
constraints:
  allowed_mime_types:
    - image/jpeg
    - image/png
  max_file_size_bytes: 10485760
meta:
  rest:
    mode: callback
    callback_ref: planogram_compliance
    response_path: "$.compliance_score"
    display_template: "Compliance: {{{{ (answer * 100) | round }}}}/100"
    persist_binary: true
```

Server-side callback registration:

```python
from parrot_formdesigner.services.callback_registry import register_form_callback

@register_form_callback("planogram_compliance")
async def planogram_compliance(input):
    # input.content contains the raw bytes
    score = await my_ml_service.analyse(input.content, input.content_type)
    return {{"compliance_score": score}}
```

Happy-path response:

```json
{{
  "success": true,
  "answer": 0.92,
  "raw_value": {{"compliance_score": 0.92}},
  "blob_ref": "s3://parrot-forms/demo/planogram_photo/a1b2c3d4.jpg",
  "display": "Compliance: 92/100",
  "warnings": [],
  "error": null
}}
```

---

## Pydantic Schema Reference

### RestFieldSpec (discriminated union)

```json
{json.dumps(spec_schema, indent=2)}
```

### RestFieldResult

```json
{json.dumps(result_schema, indent=2)}
```
"""

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(doc, encoding="utf-8")
    print(f"Generated: {out_path}")


def main() -> None:
    """Entry point for the documentation generator script."""
    parser = argparse.ArgumentParser(description="Generate REST field frontend docs")
    default_out = _SCRIPT_DIR.parent / "docs" / "frontend" / "rest-field.md"
    parser.add_argument(
        "--out",
        type=Path,
        default=default_out,
        help=f"Output path (default: {default_out})",
    )
    args = parser.parse_args()
    _generate(args.out)


if __name__ == "__main__":
    main()
