#!/usr/bin/env python3
"""Generate frontend implementation docs for FieldType.REST.

Reads RestFieldSpec / RestFieldResult Pydantic schemas plus the
x-parrot-rest JSON Schema extension shape and emits a single Markdown
file suitable for the frontend team.

Usage:
    python scripts/gen_frontend_docs.py
    python scripts/gen_frontend_docs.py --out path/to/output.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Resolve package from repo root when run as a script
# ---------------------------------------------------------------------------
_REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(_REPO_ROOT / "packages" / "parrot-formdesigner" / "src"))

from parrot_formdesigner.services.rest_field_resolver import (  # noqa: E402
    RestCallbackInput,
    RestFieldResult,
    RestFieldSpec,
    RemoteRestFieldSpec,
    InternalRestFieldSpec,
    CallbackRestFieldSpec,
)

# ---------------------------------------------------------------------------
# Default output path
# ---------------------------------------------------------------------------
_DEFAULT_OUT = (
    Path(__file__).resolve().parent.parent / "docs" / "frontend" / "rest-field.md"
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _json_block(obj: object) -> str:
    return "```json\n" + json.dumps(obj, indent=2) + "\n```"


def _schema_table(schema: dict) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    if not props:
        return "_No properties._\n"
    lines = ["| Field | Type | Required | Description |", "|---|---|---|---|"]
    for name, prop in props.items():
        typ = prop.get("type", prop.get("anyOf", [{}])[0].get("type", "any"))
        if isinstance(typ, list):
            typ = " | ".join(typ)
        req = "yes" if name in required else "no"
        desc = prop.get("description") or prop.get("title") or ""
        lines.append(f"| `{name}` | `{typ}` | {req} | {desc} |")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Document builder
# ---------------------------------------------------------------------------


def build_doc() -> str:
    remote_schema = RemoteRestFieldSpec.model_json_schema()
    internal_schema = InternalRestFieldSpec.model_json_schema()
    callback_schema = CallbackRestFieldSpec.model_json_schema()
    result_schema = RestFieldResult.model_json_schema()
    input_schema = RestCallbackInput.model_json_schema()

    x_parrot_rest_example = {
        "mode": "callback",
        "callback_ref": "planogram_analyzer",
        "timeout_seconds": 30,
        "response_path": "$.result.label",
        "display_template": "Detected: {{ value }}",
        "persist_binary": True,
    }

    planogram_yaml_example = """\
field_id: planogram_image
field_type: rest
label: Planogram Photo
constraints:
  allowed_mime_types:
    - image/jpeg
    - image/png
  max_file_size_bytes: 10485760   # 10 MB
meta:
  rest:
    mode: callback
    callback_ref: planogram_analyzer
    response_path: "$.result.label"
    display_template: "Detected: {{ value }}"
"""

    planogram_json_schema_example = {
        "type": "string",
        "title": "Planogram Photo",
        "x-parrot-rest": {
            "mode": "callback",
            "callback_ref": "planogram_analyzer",
            "response_path": "$.result.label",
            "display_template": "Detected: {{ value }}",
        },
    }

    lines: list[str] = []

    lines += [
        "# FieldType.REST — Frontend Implementation Guide",
        "",
        "> Auto-generated by `scripts/gen_frontend_docs.py`. Do not edit manually.",
        "> Re-generate with: `python scripts/gen_frontend_docs.py`",
        "",
        "---",
        "",
        "## Overview",
        "",
        "`FieldType.REST` represents a form field whose value is resolved by an",
        "external service (remote HTTP, internal loopback, or a registered Python",
        "callback). The frontend uploads a file via multipart POST and receives a",
        "structured JSON envelope.",
        "",
        "---",
        "",
        "## JSON Schema Extension: `x-parrot-rest`",
        "",
        "When the backend renders a form to JSON Schema (e.g. for an OpenAPI spec),",
        "REST fields carry the `x-parrot-rest` extension key:",
        "",
        _json_block(planogram_json_schema_example),
        "",
        "The extension shape mirrors the `RestFieldSpec` model (see §Spec Models below).",
        "",
        "---",
        "",
        "## Upload Endpoint",
        "",
        "```",
        "POST /api/v1/forms/{form_id}/fields/{field_id}/upload",
        "Content-Type: multipart/form-data",
        "Authorization: Bearer <token>",
        "X-Parrot-Prior-Blob-Ref: <previous blob URI>  (optional — triggers deletion)",
        "```",
        "",
        "### Request",
        "",
        "| Part | Required | Notes |",
        "|---|---|---|",
        "| `file` (binary part) | yes | The file to upload. Content-Type set per part. |",
        "",
        "**`X-Parrot-Prior-Blob-Ref`** — if provided, the backend deletes the previous",
        "blob after the new one is durably stored. Deletion failure does NOT cause a",
        "non-200 response; it appears as a string in `warnings`.",
        "",
        "### Error Codes",
        "",
        "| Code | Meaning |",
        "|---|---|",
        "| 400 | Malformed multipart, missing file part, or invalid REST spec |",
        "| 401 | Unauthenticated |",
        "| 404 | Form not found or field is not `FieldType.REST` |",
        "| 413 | File exceeds `constraints.max_file_size_bytes` |",
        "| 415 | MIME type not in `constraints.allowed_mime_types` |",
        "| 500 | Server misconfiguration (blob_storage or rest_resolver not wired) |",
        "",
        "### Response Envelope (HTTP 200)",
        "",
        "A `success: false` result from the resolver is returned as HTTP **200**",
        "(not 500). The frontend must inspect `success` to determine outcome.",
        "",
        _json_block({
            "success": True,
            "answer": "<JSONPath-extracted value or raw_value>",
            "raw_value": "<full resolver response>",
            "blob_ref": "s3://bucket/form_id/field_id/<uuid>",
            "display": "<Jinja2-rendered display string or null>",
            "warnings": [],
            "error": None,
        }),
        "",
        "#### Response Envelope Fields",
        "",
        _schema_table(result_schema),
        "",
        "---",
        "",
        "## Spec Models",
        "",
        "All three modes share a common base (`timeout_seconds`, `response_path`,",
        "`display_template`, `persist_binary`, `response_schema`).",
        "",
        "### `remote` mode",
        "",
        "Calls an arbitrary external HTTP endpoint.",
        "",
        _schema_table(remote_schema),
        "",
        "### `internal` mode",
        "",
        "Calls an internal loopback service (SSRF-guarded). `endpoint` must start with `/`.",
        "",
        _schema_table(internal_schema),
        "",
        "### `callback` mode",
        "",
        "Invokes a pre-registered tenant-scoped Python coroutine via `callback_ref`.",
        "",
        _schema_table(callback_schema),
        "",
        "---",
        "",
        "## Callback Input Payload",
        "",
        "Callbacks receive a `RestCallbackInput` object:",
        "",
        _schema_table(input_schema),
        "",
        "---",
        "",
        "## YAML Form Definition Example — Planogram Analyzer",
        "",
        "```yaml",
        planogram_yaml_example.rstrip(),
        "```",
        "",
        "The planogram analyzer callback (`planogram_analyzer`) receives the image",
        "bytes, runs detection, and returns a `RestCallbackOutput` with",
        "`value={\"result\": {\"label\": \"Facing OK\"}}`. The `response_path`",
        "`$.result.label` extracts `\"Facing OK\"` into `answer`, and",
        "`display_template` renders it as `\"Detected: Facing OK\"`.",
        "",
        "---",
        "",
        "## Integration Checklist",
        "",
        "- [ ] Render `FieldType.REST` fields as a file-upload input.",
        "- [ ] On upload, `POST` multipart to the upload endpoint.",
        "- [ ] Attach `Authorization: Bearer <token>` (session token).",
        "- [ ] Attach `X-Parrot-Prior-Blob-Ref` if re-uploading to the same field.",
        "- [ ] Inspect `success` in the response envelope (200 ≠ success).",
        "- [ ] Display `display` string if present, otherwise fall back to `answer`.",
        "- [ ] Surface `warnings[]` to the user if non-empty.",
        "- [ ] Show `error` message when `success: false`.",
        "",
    ]

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=_DEFAULT_OUT,
        help="Output Markdown file path (default: docs/frontend/rest-field.md)",
    )
    args = parser.parse_args()

    out: Path = args.out
    out.parent.mkdir(parents=True, exist_ok=True)

    content = build_doc()
    out.write_text(content, encoding="utf-8")
    print(f"Generated: {out}")


if __name__ == "__main__":
    main()
