"""ResearchNode — bug triage, Jira ticket, sdd-research dispatch.

Implements **Module 5** of the dev-loop spec. Sequence (per spec §3 M5):

1. Fetch logs via the configured log toolkits (one per ``LogSource.kind``).
2. Create the Jira ticket via ``jira_toolkit.jira_create_issue(...)``.
   The ticket is created **before** the dispatch — the call order is
   pinned by a unit test (spec §4 ``test_research_node_creates_jira_then_dispatches``).
   FEAT-132: the issuetype is derived from ``brief.kind`` via
   ``_ISSUE_TYPE_BY_KIND``. On the create path, the plan summary is
   generated by ``_build_plan_summary`` and posted as the first comment.
3. Dispatch to the ``sdd-research`` subagent so it runs ``/sdd-spec``,
   ``/sdd-task``, and creates the worktree.
4. Validate the dispatch payload as :class:`ResearchOutput` (delegated
   to the dispatcher's output_model contract).

Spec §7 R5 — duplicate worktree detection: the node checks
``WORKTREE_BASE_PATH/<branch_name>`` after the subagent returns and
fails fast if the directory exists; recovery is the human's job.
"""

from __future__ import annotations

import asyncio
import os
import re
from typing import Any, Dict, List, Optional, Union

from navconfig import BASE_DIR

from parrot import conf
from parrot.bots.flows.core.context import FlowContext
from parrot.bots.flows.core.types import DependencyResults
from parrot.clients.factory import LLMFactory
from parrot.flows.dev_loop.dispatcher import ClaudeCodeDispatcher
from parrot.flows.dev_loop.models import (
    BugBrief,
    ClaudeCodeDispatchProfile,
    LogSource,
    RepoSpec,
    ResearchOutput,
    WorkBrief,
)
from parrot.flows.dev_loop.nodes.base import DevLoopNode, register_dev_loop_node


# Atlassian caps the description field at 32 767 chars; leave a 2K
# headroom for the rest of the JSON body and any unicode-byte expansion.
_MAX_DESCRIPTION_CHARS = 30_000
# Target size for the LLM-summarized excerpts block when the raw body
# would exceed _MAX_DESCRIPTION_CHARS. Keeps the digest compact enough
# that the surrounding sections (criteria, reporter, user description)
# always fit.
_SUMMARIZED_EXCERPTS_CHARS = 8_000

# Max number of cleaned log lines kept per source after noise filtering.
# CloudWatch Insights returns up to 100 rows; the vast majority are health
# probes and framework chatter, so a small tail of *meaningful* lines is
# all a human triager (or the research subagent) actually needs.
_MAX_CLEAN_LOG_LINES = 25

# Health-check / probe / framework-chatter lines that carry no incident
# signal. Dropped before excerpts ever reach the Jira ticket or the
# research prompt. Matched case-insensitively against the @message text.
_LOG_NOISE_RE = re.compile(
    r"""
      kube-probe                       # k8s liveness/readiness probes
    | /healthz?\b                      # GET /health or /healthz endpoints
    | "GET\s+/health                   # access-log health hits
    | httplog\.go.*?/healthz           # apiserver healthz access logs
    | Rendered\s                       # Rails view rendering
    | Processing\s+by\s.*Controller\#  # Rails controller dispatch
    | Started\s+GET\s+"/"              # Rails root probe
    """,
    re.IGNORECASE | re.VERBOSE,
)

# CloudWatch system fields that are pure cursor/pagination noise — never
# useful to a human and they dominate the byte count of a raw dump.
_LOG_DROP_FIELDS = frozenset({"@ptr"})

# FEAT-132: Jira issuetype per work-kind.
# Keys are the three WorkKind literals; values are the Jira issuetype
# labels accepted by the NAV Jira instance (verified 2026-04-28).
_ISSUE_TYPE_BY_KIND: Dict[str, str] = {
    "bug": "Bug",
    "enhancement": "Story",
    "new_feature": "New Feature",
}


def _summarizer_llm_default() -> str:
    """Resolve the default LLM string for log-excerpt summarization.

    Reads ``DEV_LOOP_SUMMARY_LLM`` from navconfig (env-overridable);
    falls back to Anthropic Haiku 4.5 — small, fast, cheap, perfect
    for compressing a few KB of log into a digest.
    """
    return conf.config.get(
        "DEV_LOOP_SUMMARY_LLM",
        fallback="anthropic:claude-haiku-4-5-20251001",
    )


def _plan_llm_default() -> str:
    """Resolve the plan-summary LLM string (FEAT-132).

    Returns the value of ``DEV_LOOP_PLAN_LLM`` when set, otherwise
    falls back to the same model as :func:`_summarizer_llm_default`.
    An empty ``DEV_LOOP_PLAN_LLM`` means "use the summarizer default".
    """
    pinned = conf.DEV_LOOP_PLAN_LLM
    if pinned:
        return pinned
    return _summarizer_llm_default()


@register_dev_loop_node("dev_loop.research")
class ResearchNode(DevLoopNode):
    """Second node — Jira + log fetch + sdd-research dispatch.

    Args:
        dispatcher: A :class:`ClaudeCodeDispatcher` instance shared by
            every node in the flow.
        jira_toolkit: A pre-built ``parrot_tools.jiratoolkit.JiraToolkit``
            wired with service-account credentials.
        log_toolkits: Mapping ``"cloudwatch"|"elasticsearch"`` →
            toolkit instance. Optional kinds may be missing; an unknown
            ``LogSource.kind`` raises ``ValueError`` at dispatch time.
        name: Node id, default ``"research"``.
    """

    def __init__(
        self,
        *,
        dispatcher: ClaudeCodeDispatcher,
        jira_toolkit: Any,
        log_toolkits: Optional[Dict[str, Any]] = None,
        summarizer_llm: Optional[str] = None,
        plan_llm: Optional[str] = None,
        git_toolkit: Optional[Any] = None,
        repos: Optional[List[RepoSpec]] = None,
        name: str = "research",
    ) -> None:
        super().__init__(node_id=name)
        object.__setattr__(self, "_dispatcher", dispatcher)
        object.__setattr__(self, "_jira", jira_toolkit)
        # FEAT-250: optional repo provisioning before Development. When
        # ``repos`` is empty the node behaves exactly as before (no clone).
        object.__setattr__(self, "_git_toolkit", git_toolkit)
        object.__setattr__(self, "_repos", list(repos or []))
        object.__setattr__(self, "_log_toolkits", log_toolkits or {})
        object.__setattr__(self, "_summarizer_llm", summarizer_llm or _summarizer_llm_default())
        object.__setattr__(self, "_summarizer_client", None)
        object.__setattr__(self, "_plan_llm", plan_llm or _plan_llm_default())
        object.__setattr__(self, "_plan_client", None)

    # ------------------------------------------------------------------
    # Execute
    # ------------------------------------------------------------------

    async def execute(
        self,
        ctx: Union[FlowContext, Dict[str, Any]],
        deps: Optional[DependencyResults] = None,
        **kwargs: Any,
    ) -> ResearchOutput:
        """Run the research phase. Returns a validated :class:`ResearchOutput`.

        Reads ``bug_brief`` and ``run_id`` from the shared state; writes
        ``jira_issue_key``, ``log_excerpts``, and ``research_output``.
        """
        shared = self.shared_state(ctx)
        brief: BugBrief = shared["bug_brief"]

        # 1. Fetch logs first — cheap, deterministic, and the excerpts
        # become part of the Jira description.
        excerpts = await self._collect_log_excerpts(brief.log_sources)

        # 2. Resolve the Jira ticket BEFORE dispatching. Unit tests pin
        # this ordering (spec §4 test_research_node_creates_jira_then_dispatches).
        # Idempotency: reuse an existing ticket when one already tracks
        # this incident (caller-supplied ``existing_issue_key`` or an
        # open ticket whose summary matches verbatim). Otherwise, fall
        # back to creating a new one. Reporter is resolved to an
        # accountId here (the toolkit auto-resolves the assignee but
        # not the raw fields={"reporter":…} blob, so we do it
        # explicitly so emails work in BugBrief.reporter).
        description = await self._build_description(brief, excerpts)
        existing_key = await self._find_existing_issue(brief)
        if existing_key:
            issue_key = existing_key
            self.logger.info(
                "Re-using existing Jira ticket %s for run_id=%s",
                issue_key, shared.get("run_id", "?"),
            )
            await self._comment_retriggered(
                issue_key=issue_key,
                run_id=shared.get("run_id", ""),
                description=description,
            )
        else:
            reporter_fields = await self._reporter_fields(brief.reporter)
            # FEAT-132: pick the issuetype from the kind→type mapping.
            issuetype = _ISSUE_TYPE_BY_KIND.get(
                getattr(brief, "kind", "bug"), "Bug"
            )
            jira_resp = await self._jira.jira_create_issue(
                summary=brief.summary,
                issuetype=issuetype,
                description=description,
                assignee=conf.FLOW_BOT_JIRA_ACCOUNT_ID or None,
                fields=reporter_fields,
            )
            issue_key = self._extract_issue_key(jira_resp)
            self.logger.info(
                "Created new Jira ticket %s (kind=%s) for run_id=%s",
                issue_key, getattr(brief, "kind", "bug"), shared.get("run_id", "?"),
            )
            # FEAT-132 G4: post plan-summary as first comment on new tickets.
            run_id = shared.get("run_id", "")
            plan = await self._build_plan_summary(brief, excerpts)
            await self._post_plan_summary_comment(
                issue_key=issue_key, plan=plan, run_id=run_id
            )
        shared["jira_issue_key"] = issue_key

        # 3. FEAT-253: Provision repos BEFORE the sdd-research dispatch so
        # the dispatch cwd is set correctly (clone path when a repo is
        # declared, WORKTREE_BASE_PATH when local).
        # _provision_repos now returns str(BASE_DIR) when no repos are
        # configured (local fallback) and the clone path otherwise.
        repo_path = await self._provision_repos(shared.get("run_id", ""))
        is_clone = bool(self._repos and self._git_toolkit is not None)
        dispatch_cwd: str = (
            repo_path if is_clone else os.path.abspath(conf.WORKTREE_BASE_PATH)
        )
        self.logger.info(
            "Base repository: %s (clone=%s), dispatch cwd: %s",
            repo_path, is_clone, dispatch_cwd,
        )

        # 4. Dispatch the sdd-research subagent.
        profile = ClaudeCodeDispatchProfile(
            subagent="sdd-research",
            permission_mode="acceptEdits",
            # SlashCommand: the subagent runs /sdd-spec and /sdd-task.
            # Write: it scaffolds spec/task files under sdd/. Read/Grep/Glob
            # for triage, Bash for git worktree plumbing.
            allowed_tools=[
                "Read", "Grep", "Glob", "Bash", "Write", "SlashCommand",
            ],
            model="claude-sonnet-4-6",
        )
        os.makedirs(dispatch_cwd, exist_ok=True)
        # Stash the excerpts on the brief so the subagent gets them.
        # We pass the brief through as-is since BugBrief already carries
        # log_sources; the prompt builder embeds excerpts separately.
        shared["log_excerpts"] = excerpts

        research_out: ResearchOutput = await self._dispatcher.dispatch(
            brief=brief,
            profile=profile,
            output_model=ResearchOutput,
            run_id=shared["run_id"],
            node_id=self.name,
            cwd=dispatch_cwd,
            # FEAT-322: fold dispatch-level events into the run's
            # SessionHost when one is present (see development.py's
            # dispatch() call for the same pattern/rationale).
            session_host=shared.get("session_host"),
        )

        # 5. If the subagent left jira_issue_key blank, inject ours.
        if not research_out.jira_issue_key:
            research_out = research_out.model_copy(
                update={"jira_issue_key": issue_key}
            )

        # 6. Spec §7 R5 (relaxed) — reuse existing worktree if it's
        # already a registered git worktree on the expected branch;
        # fail fast only on the unsafe shapes (untracked directory or
        # mismatched branch).
        await self._ensure_worktree_safe(research_out.branch_name)

        # 7. Set repo_path on the output to record the base repository.
        # repo_path is str(BASE_DIR) (local) or the clone path (declared
        # repo). worktree_path remains the per-run worktree — distinct from
        # repo_path (FEAT-253 G2/G3).
        research_out = research_out.model_copy(
            update={"repo_path": repo_path}
        )

        shared["research_output"] = research_out
        return research_out

    # ------------------------------------------------------------------
    # Internal — repo provisioning (FEAT-250)
    # ------------------------------------------------------------------

    async def _provision_repos(self, run_id: str) -> str:
        """Clone/pull each configured ``RepoSpec``; return the base repo path.

        **Local fallback (FEAT-253 G2)**: when no repos are declared or no
        ``git_toolkit`` is set, the base repository is the local checkout at
        ``BASE_DIR``. Returns ``str(BASE_DIR)`` (no clone; worktree will be
        branched from the outer ``BASE_DIR`` repo by the ``sdd-research``
        dispatch).

        **Declared-repo path (FEAT-253 G3)**: the primary repo (first
        ``RepoSpec``) is cloned/pulled into
        ``<DEV_LOOP_REPO_BASE_PATH>/<run_id>/<alias>`` — anchored under
        ``WORKTREE_BASE_PATH`` so the dispatcher's cwd-safety guard passes.
        Returns the clone path (the base repository from which the worktree
        will be created). Secondary repos are **not** cloned in v1.

        Never logs tokens — :class:`GitToolkit` handles scrubbing internally.
        """
        if not self._repos or self._git_toolkit is None:
            self.logger.info(
                "No repos declared; base repository = BASE_DIR (%s)", BASE_DIR
            )
            return str(BASE_DIR)

        base = os.path.join(
            os.path.abspath(conf.DEV_LOOP_REPO_BASE_PATH), run_id or "run"
        )
        os.makedirs(base, exist_ok=True)

        primary_path = ""
        for idx, repo in enumerate(self._repos):
            dest = os.path.join(base, repo.alias)

            # Defense-in-depth: alias already validated by RepoSpec, but guard
            # against any normpath escape that slips through at the OS level.
            if not os.path.normpath(dest).startswith(os.path.normpath(base)):
                raise ValueError(
                    f"RepoSpec alias {repo.alias!r} would escape the clone "
                    f"base {base!r} — refusing to provision."
                )

            self.logger.info(
                "Provisioning repo %r → %s (branch=%s, private=%s)",
                repo.alias, dest, repo.branch, repo.private,
            )
            try:
                result = await self._git_toolkit.clone_repo(
                    repo.url,
                    dest,
                    branch=repo.branch,
                    private=repo.private,
                )
            except Exception as exc:
                self.logger.error(
                    "Failed to provision repo %r → %s: %s. "
                    "Falling back to local BASE_DIR checkout.",
                    repo.alias, dest, exc,
                )
                return str(BASE_DIR)
            path = result.get("path", dest) if isinstance(result, dict) else dest
            if idx == 0:
                primary_path = path
        return primary_path

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _collect_log_excerpts(
        self, sources: List[LogSource]
    ) -> List[str]:
        excerpts: List[str] = []
        for src in sources:
            try:
                excerpts.extend(await self._fetch_logs(src))
            except Exception as exc:  # never block the flow on log fetch
                self.logger.warning(
                    "Log fetch failed for %s/%s: %s", src.kind, src.locator, exc
                )
        return excerpts

    async def _fetch_logs(self, source: LogSource) -> List[str]:
        if source.kind == "cloudwatch":
            toolkit = self._log_toolkits.get("cloudwatch")
            if toolkit is None:
                raise ValueError("CloudWatch toolkit not configured")
            # Per project policy the log group is configured at toolkit
            # construction time (default_log_group); the per-source
            # locator is informational and only forwarded if a non-empty
            # override is provided.
            kwargs: Dict[str, Any] = {
                "start_time": f"-{source.time_window_minutes}m",
            }
            if source.locator and source.locator != toolkit.default_log_group:
                kwargs["log_group_name"] = source.locator
            result = await toolkit.aws_cloudwatch_query_logs(**kwargs)
            return self._tail_text(result)
        if source.kind == "elasticsearch":
            toolkit = self._log_toolkits.get("elasticsearch")
            if toolkit is None:
                raise ValueError("Elasticsearch toolkit not configured")
            result = await toolkit.search(
                index=source.locator,
                window_minutes=source.time_window_minutes,
            )
            return self._tail_text(result)
        if source.kind == "attached_file":
            # Blocking I/O off the event loop — large attached log files
            # would otherwise stall every concurrent flow run.
            content = await asyncio.to_thread(
                self._read_file_tail, source.locator, 4000
            )
            return [content]
        raise ValueError(f"Unknown log source kind: {source.kind}")

    @staticmethod
    def _read_file_tail(path: str, max_bytes: int) -> str:
        """Synchronous helper run via :func:`asyncio.to_thread`."""
        with open(path, "r", encoding="utf-8") as fh:
            return fh.read()[-max_bytes:]

    @classmethod
    def _tail_text(cls, result: Any) -> List[str]:
        # CloudWatch Insights / structured log-event payloads arrive as
        # ``{"results": [{"@timestamp": ..., "@message": ..., "@ptr": ...}]}``.
        # Stringifying that dict dumps base64 ``@ptr`` cursors and every
        # health-probe line straight into the Jira ticket, which is useless
        # noise — so clean + filter at the source instead.
        if isinstance(result, dict):
            rows = result.get("results") or result.get("events")
            if isinstance(rows, list) and rows:
                cleaned = cls._clean_log_rows(rows)
                if cleaned:
                    return cleaned
        if isinstance(result, str):
            return [result[-4000:]]
        if isinstance(result, list):
            # A bare list of structured rows (no enclosing envelope).
            if result and isinstance(result[0], dict):
                cleaned = cls._clean_log_rows(result)
                if cleaned:
                    return cleaned
            return [str(x)[-4000:] for x in result[-10:]]
        return [str(result)[-4000:]]

    @classmethod
    def _clean_log_rows(cls, rows: List[Any]) -> List[str]:
        """Reduce structured log rows to a compact ``[ts] message`` digest.

        Drops cursor fields (``@ptr``), filters health-probe / framework
        chatter, and keeps only the last :data:`_MAX_CLEAN_LOG_LINES`
        meaningful lines. If every row is noise, falls back to the tail of
        the raw (``@ptr``-stripped) lines so an empty block is never emitted.

        Args:
            rows: Structured log records (dicts) or pre-formatted strings.

        Returns:
            A list of cleaned single-line strings (newest last). Returned as
            a single-element list so the surrounding excerpt joiner keeps one
            digest per source.
        """
        formatted: List[str] = []
        for row in rows:
            if isinstance(row, dict):
                fields = {
                    k: v for k, v in row.items() if k not in _LOG_DROP_FIELDS
                }
                message = str(
                    fields.get("@message") or fields.get("message") or ""
                ).strip()
                if not message:
                    # No message field — keep a compact repr of the rest.
                    message = str(fields).strip()
                timestamp = str(
                    fields.get("@timestamp") or fields.get("timestamp") or ""
                ).strip()
                line = f"[{timestamp}] {message}" if timestamp else message
            else:
                line = str(row).strip()
            if line:
                formatted.append(line)

        meaningful = [ln for ln in formatted if not _LOG_NOISE_RE.search(ln)]
        kept = (meaningful or formatted)[-_MAX_CLEAN_LOG_LINES:]
        if not kept:
            return []
        return ["\n".join(kept)]

    async def _build_description(
        self, brief: BugBrief, excerpts: List[str]
    ) -> str:
        """Render the Jira description, summarizing logs if it overflows.

        Progressive degradation:

        1. Render the full body with raw excerpts.
        2. If the result would exceed Atlassian's 32 767-char cap, send
           the excerpts through an LLM summarizer (Haiku by default) and
           re-render with the digest in place of the raw text.
        3. As a last-resort defense, hard-truncate to
           ``_MAX_DESCRIPTION_CHARS`` with a ``... (truncated)`` marker.

        The user-supplied ``brief.description`` is never summarized — it
        is the human's own words and stays verbatim until the final
        truncation step (which only kicks in if even the digest version
        is too long, and is logged loudly).
        """
        body = self._render_body(brief, excerpts)
        if len(body) > _MAX_DESCRIPTION_CHARS:
            self.logger.info(
                "Description %d chars > %d cap; summarizing log excerpts",
                len(body), _MAX_DESCRIPTION_CHARS,
            )
            digest = await self._summarize_excerpts(excerpts)
            body = self._render_body(
                brief,
                [
                    "(Auto-summarized: the raw log excerpts exceeded "
                    "Jira's 32 767-char limit. The digest below was "
                    f"produced by {self._summarizer_llm}.)\n\n"
                    + digest
                ],
            )
        if len(body) > _MAX_DESCRIPTION_CHARS:
            self.logger.warning(
                "Description still %d chars after summarization; "
                "hard-truncating to %d.",
                len(body), _MAX_DESCRIPTION_CHARS,
            )
            body = (
                body[: _MAX_DESCRIPTION_CHARS - 32].rstrip()
                + "\n\n... (truncated)"
            )
        return body

    @staticmethod
    def _render_body(brief: BugBrief, excerpts: List[str]) -> str:
        # Format each criterion with the salient field for human review:
        # shell command for ShellCriterion, task_path for FlowtaskCriterion,
        # raw text for ManualCriterion.
        def _fmt_criterion(c: Any) -> str:
            kind = getattr(c, "kind", "?")
            name = getattr(c, "name", "?")
            detail = (
                getattr(c, "command", None)
                or getattr(c, "task_path", None)
                or getattr(c, "text", "")
            )
            return f"- [{kind}] {name}: {detail}"

        criteria_lines = "\n".join(
            _fmt_criterion(c) for c in brief.acceptance_criteria
        )
        excerpts_block = "\n---\n".join(excerpts) if excerpts else "(none)"
        details_block = (
            f"Details:\n{brief.description}\n\n" if brief.description else ""
        )
        return (
            f"Affected component: {brief.affected_component}\n\n"
            f"{details_block}"
            f"Acceptance criteria:\n{criteria_lines}\n\n"
            f"Log excerpts:\n{excerpts_block}\n\n"
            f"Reporter: {brief.reporter}\n"
            f"Escalation assignee on failure: {brief.escalation_assignee}\n"
        )

    async def _summarize_excerpts(self, excerpts: List[str]) -> str:
        """Compress raw log excerpts into a concise incident digest.

        Falls back to a deterministic tail-truncation when the LLM call
        fails or no API key is available — the flow never crashes
        because of the summarizer.
        """
        raw = "\n---\n".join(excerpts) if excerpts else ""
        if not raw:
            return "(no log excerpts available)"
        target_chars = _SUMMARIZED_EXCERPTS_CHARS
        try:
            client = self._get_summarizer_client()
            prompt = (
                "You are summarising application log excerpts so a human "
                "engineer can triage an incident from a Jira ticket.\n\n"
                "Produce a concise digest — at most "
                f"{target_chars // 6} words. Highlight: error messages, "
                "stack frames, repeated symptoms, request IDs, "
                "timestamps, and any obvious root-cause hints. Quote "
                "the most damning lines verbatim. Do NOT add prose "
                "beyond the digest itself.\n\n"
                "===LOGS START===\n"
                f"{raw}\n"
                "===LOGS END==="
            )
            response = await client.ask(prompt, max_tokens=2000)
            text = (response.response or "").strip()
            if text:
                return text
        except Exception as exc:  # noqa: BLE001 - degraded fallback
            self.logger.warning(
                "Log summarization via %s failed (%s); "
                "falling back to deterministic tail",
                self._summarizer_llm, exc,
            )
        # Deterministic fallback: keep the tail of each excerpt up to
        # the target budget.
        budget = max(target_chars // max(1, len(excerpts)), 200)
        tails = [e[-budget:] for e in excerpts]
        return "\n---\n".join(tails)

    def _get_summarizer_client(self) -> Any:
        if self._summarizer_client is None:
            self._summarizer_client = LLMFactory.create(self._summarizer_llm)
        return self._summarizer_client

    # ------------------------------------------------------------------
    # FEAT-132 — Plan-summary helpers
    # ------------------------------------------------------------------

    async def _build_plan_summary(
        self, brief: WorkBrief, excerpts: List[str]
    ) -> str:
        """Generate a short action-oriented plan for the Jira ticket comment.

        Uses the plan LLM (``DEV_LOOP_PLAN_LLM`` or falls back to the
        summary LLM). Falls back to a deterministic stub when the LLM
        call fails so the flow never aborts because of this helper.

        Args:
            brief: The validated :class:`WorkBrief` for this run.
            excerpts: Pre-collected log excerpts (may be empty).

        Returns:
            A plan string suitable for posting as a Jira comment body.
        """
        try:
            client = self._get_plan_client()
            prompt = self._compose_plan_prompt(brief, excerpts)
            response = await client.ask(prompt, max_tokens=1200)
            text = (response.response or "").strip()
            if text:
                return text
        except Exception as exc:  # noqa: BLE001 - degraded fallback
            self.logger.warning(
                "Plan summarization via %s failed (%s); "
                "falling back to deterministic stub",
                self._plan_llm, exc,
            )
        return self._deterministic_plan_stub(brief)

    @staticmethod
    def _compose_plan_prompt(
        brief: WorkBrief, excerpts: List[str]
    ) -> str:
        """Build the plan-generation prompt consumed by the plan LLM.

        Args:
            brief: The work brief for this run.
            excerpts: Log excerpts (may be empty).

        Returns:
            A single string combining a system frame and user content.
        """
        return (
            "You are an SRE planning a fix or change for a Jira ticket. "
            "Read the request and produce a SHORT actionable plan "
            "(max 8 bullet points) describing the steps you would take "
            "to resolve it. Reference modules / files when obvious from "
            "the description. Do not quote logs verbatim and do not "
            "restate the summary.\n\n"
            f"Kind: {getattr(brief, 'kind', 'bug')}\n"
            f"Summary: {brief.summary}\n"
            f"Component: {brief.affected_component}\n"
            f"Description: {brief.description or '(none)'}\n"
            "Log excerpts (truncated):\n"
            + ("\n---\n".join(excerpts) if excerpts else "(none)")
        )

    @staticmethod
    def _deterministic_plan_stub(brief: WorkBrief) -> str:
        """Return a deterministic fallback plan when the LLM fails.

        Args:
            brief: The work brief; used to supply context in the stub text.

        Returns:
            A short stub string that is safe to post as a Jira comment.
        """
        return (
            f"Plan unavailable (LLM call failed). Manual triage "
            f"required for kind={getattr(brief, 'kind', 'bug')!r}, "
            f"component {brief.affected_component!r}."
        )

    async def _post_plan_summary_comment(
        self,
        *,
        issue_key: str,
        plan: str,
        run_id: str,
    ) -> None:
        """Post the plan summary as the first comment on the new ticket.

        Args:
            issue_key: The Jira ticket key (e.g. ``'NAV-123'``).
            plan: The plan text returned by :meth:`_build_plan_summary`.
            run_id: The flow run identifier included in the comment header.
        """
        body = f"Plan for run-{run_id}\n\n{plan}"
        try:
            await self._jira.jira_add_comment(issue=issue_key, body=body)
        except Exception as exc:  # noqa: BLE001 - non-fatal
            self.logger.warning(
                "Could not post plan-summary comment on %s: %s",
                issue_key, exc,
            )

    def _get_plan_client(self) -> Any:
        """Return the cached plan LLM client, creating it on first call.

        Returns:
            A live LLM client instance (same interface as the summarizer).
        """
        if self._plan_client is None:
            self._plan_client = LLMFactory.create(self._plan_llm)
        return self._plan_client

    async def _find_existing_issue(self, brief: BugBrief) -> Optional[str]:
        """Look up a Jira ticket that already tracks this incident.

        Two-tier lookup:

        1. Caller-provided ``brief.existing_issue_key`` — verified via
           ``jira_get_issue`` so we don't trust a stale value.
        2. JQL search by exact summary in the configured project,
           filtered to tickets that aren't ``Done``. Multiple matches
           pick the most recent (the JQL orders by ``created DESC``).

        Returns:
            The Jira issue key on hit, ``None`` otherwise.
        """
        # 1. Caller override.
        if brief.existing_issue_key:
            try:
                result = await self._jira.jira_get_issue(brief.existing_issue_key)
            except Exception as exc:  # noqa: BLE001 - degrade to lookup
                self.logger.warning(
                    "existing_issue_key=%r could not be fetched (%s); "
                    "falling back to summary search",
                    brief.existing_issue_key, exc,
                )
            else:
                # Toolkit responses carry a "status" key; treat a missing
                # key as success so a bare issue payload also counts as a hit.
                status = (
                    result.get("status", "ok")
                    if isinstance(result, dict) else "ok"
                )
                if status == "ok":
                    return brief.existing_issue_key
                self.logger.warning(
                    "existing_issue_key=%r returned %s; falling back",
                    brief.existing_issue_key, status,
                )

        # 2. Summary search inside the configured project.
        project = conf.config.get("JIRA_PROJECT")
        if not project:
            self.logger.warning(
                "JIRA_PROJECT not configured; duplicate-ticket JQL search skipped "
                "— every intake will create a new ticket even if one already exists."
            )
            return None
        # Escape JQL string delimiters in the summary.
        safe_summary = brief.summary.replace("\\", "\\\\").replace('"', '\\"')
        jql = (
            f'project = "{project}" '
            f'AND summary ~ "\\"{safe_summary}\\"" '
            f"AND statusCategory != Done "
            f"ORDER BY created DESC"
        )
        result = await self._jira.jira_search_issues(
            jql=jql,
            max_results=10,
            fields="key,summary,status",
        )
        if result["status"] == "empty":
            issues = []
        elif result["status"] == "ok":
            issues = result["data"]["issues"]
        else:
            self.logger.warning(
                "Jira lookup failed: %s", result["message"],
            )
            return None
        # JQL `~` is fuzzy — verify the exact summary post-fetch so we
        # don't mistakenly merge unrelated tickets that share keywords.
        exact_matches = [
            issue for issue in issues
            if (
                (issue.get("fields") or {}).get("summary") == brief.summary
                or issue.get("summary") == brief.summary
            )
        ]
        if not exact_matches:
            return None
        if len(exact_matches) > 1:
            self.logger.warning(
                "Found %d open Jira tickets with summary=%r; reusing "
                "the most recently created one",
                len(exact_matches), brief.summary,
            )
        chosen = exact_matches[0]
        return chosen.get("key") or chosen.get("issue_key")

    async def _comment_retriggered(
        self,
        *,
        issue_key: str,
        run_id: str,
        description: str,
    ) -> None:
        """Append a re-triggered comment to a reused Jira ticket.

        Keeps the audit trail intact when the dev-loop runs against an
        already-known incident: the original ticket gets a comment with
        the new run_id and the freshly-collected log digest, so the
        human reviewer sees that the agent re-attacked the same issue.
        """
        body = (
            f"Dev-loop re-triggered for this ticket "
            f"(run_id=`{run_id or 'unknown'}`).\n\n"
            f"Refreshed context attached:\n\n{description}"
        )
        try:
            await self._jira.jira_add_comment(issue=issue_key, body=body)
        except Exception as exc:  # noqa: BLE001 - non-fatal
            self.logger.warning(
                "Could not post re-trigger comment on %s: %s",
                issue_key, exc,
            )

    async def _reporter_fields(
        self, reporter: str
    ) -> Optional[Dict[str, Any]]:
        """Build the ``fields={"reporter": {...}}`` blob for create_issue.

        Accepts either an email or an accountId. Emails are resolved to an
        accountId via the toolkit's public ``jira_find_user`` lookup so
        callers can keep ``BugBrief.reporter`` in human-readable form
        (e.g. ``jane@example.com``) rather than the Jira-internal
        ``557058:abc`` accountId.

        The reporter slot on Jira Cloud only accepts an ``accountId`` — an
        email there is rejected with ``400 Specify a valid value for
        reporter``. If the value is an email and resolution fails (user not
        found or the lookup errors), we omit the reporter field entirely so
        the create still succeeds with the authenticated service account as
        reporter, rather than failing the whole ticket creation.

        Args:
            reporter: An accountId (used verbatim) or an email to resolve.

        Returns:
            A ``{"reporter": {"accountId": ...}}`` blob, or ``None`` to omit
            the reporter field.
        """
        if not reporter:
            return None
        account_id = await self._resolve_reporter_account_id(reporter)
        if not account_id:
            return None
        return {"reporter": {"accountId": account_id}}

    async def _resolve_reporter_account_id(self, reporter: str) -> str:
        """Resolve an email to a Jira accountId; pass accountIds through.

        We use the toolkit's *public* ``jira_find_user`` rather than the
        private ``_resolve_account_id`` because private API is not part of
        the toolkit's contract and may change without notice.

        Args:
            reporter: An accountId (returned as-is) or an email to resolve.

        Returns:
            The resolved accountId, or ``""`` when the email cannot be
            resolved (caller then omits the reporter field).
        """
        if "@" not in reporter:
            return reporter  # already an accountId
        try:
            result = await self._jira.jira_find_user(reporter)
        except Exception as exc:  # noqa: BLE001 — never fail ticket creation
            self.logger.warning(
                "Could not resolve reporter %r to an accountId: %s; "
                "omitting reporter field", reporter, exc,
            )
            return ""
        matches = (result or {}).get("matches") or []
        if not (result or {}).get("found") or not matches:
            self.logger.warning(
                "No Jira user found for reporter %r; omitting reporter field",
                reporter,
            )
            return ""
        for match in matches:
            if (match.get("emailAddress") or "").lower() == reporter.lower():
                return match["accountId"]
        return matches[0]["accountId"]

    @staticmethod
    def _extract_issue_key(resp: Any) -> str:
        if isinstance(resp, dict):
            key = resp.get("key") or resp.get("issue_key")
            if isinstance(key, str):
                return key
        return ""

    async def _ensure_worktree_safe(self, branch_name: str) -> None:
        """Verify the resolved worktree is safe to reuse, or fail loudly.

        Idempotency relaxation of spec §7 R5: when the dev-loop
        re-runs against an already-known incident, the same FEAT-id —
        and therefore the same worktree path / branch — is expected to
        appear again. Failing fast on every such re-run defeats the
        re-trigger workflow.

        Decision matrix:

        * Path does not exist → nothing to do (subagent created it).
        * Path is a registered git worktree on the *expected* branch →
          log info and reuse silently.
        * Path is a registered git worktree on a *different* branch →
          fail fast (real conflict).
        * Path exists but is NOT a registered git worktree → fail
          fast (stale junk; refuse to assume).
        * ``git worktree list`` itself failed → fail fast (cannot
          decide safely).

        Uses :func:`asyncio.create_subprocess_exec` to avoid blocking
        the event loop while git inspects the worktree list.
        """
        path = os.path.join(conf.WORKTREE_BASE_PATH, branch_name)
        if not os.path.exists(path):
            return

        try:
            proc = await asyncio.create_subprocess_exec(
                "git", "worktree", "list", "--porcelain",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout_bytes, _ = await proc.communicate()
            if proc.returncode != 0:
                raise RuntimeError(f"git exited with code {proc.returncode}")
            stdout = stdout_bytes.decode()
        except FileNotFoundError as exc:
            raise RuntimeError(
                f"Path {path!r} exists but `git worktree list` "
                f"failed: {exc}. Investigate manually before retrying."
            ) from exc
        except RuntimeError:
            raise
        except Exception as exc:
            raise RuntimeError(
                f"Path {path!r} exists but `git worktree list` "
                f"failed: {exc}. Investigate manually before retrying."
            ) from exc

        info = self._find_worktree_entry(stdout, os.path.abspath(path))
        if info is None:
            raise RuntimeError(
                f"Path {path!r} already exists but is not a registered "
                f"git worktree — likely stale. Remove it (e.g. "
                f"`rm -rf {path}`) and retry."
            )
        actual_branch = info.get("branch")
        if actual_branch and actual_branch != branch_name:
            raise RuntimeError(
                f"Worktree {path!r} is on branch {actual_branch!r}, "
                f"not on the expected {branch_name!r}. Run "
                f"`git worktree remove {path}` and retry."
            )
        self.logger.info(
            "Reusing existing worktree %s on branch %s",
            path, branch_name,
        )

    @staticmethod
    def _find_worktree_entry(
        porcelain: str, abs_path: str
    ) -> Optional[Dict[str, str]]:
        """Parse ``git worktree list --porcelain`` output for a path.

        Returns a dict with the entry's fields (notably ``branch``,
        without the ``refs/heads/`` prefix) or ``None`` if the path is
        not registered.
        """
        current: Dict[str, str] = {}
        for line in porcelain.splitlines():
            if not line:
                # Blank line separates worktree entries.
                if current.get("worktree") == abs_path:
                    return current
                current = {}
                continue
            if " " in line:
                key, _, value = line.partition(" ")
            else:
                key, value = line, ""
            if key == "branch" and value.startswith("refs/heads/"):
                value = value[len("refs/heads/"):]
            current[key] = value
        if current.get("worktree") == abs_path:
            return current
        return None


__all__ = ["ResearchNode"]
