"""Tier policy for the test-scope kernel (FEAT-563). Stdlib only — data, not logic."""

from __future__ import annotations

from dataclasses import dataclass

AGENT_MARKER_EXPRESSION: str = "not e2e and not real_llm and not integration"
AGENT_FLAGS: tuple[str, ...] = ("-q", "--tb=short", "-p", "no:cacheprovider", "-o", "log_cli=false")
DEFAULT_IMPACT_CAP: int = 150
DEFAULT_IMPACT_DEPTH: int = 1
# FEAT-620: direct-importer count, recalibrated 2026-10-01 on dev@76a7d7b22 over 2688
# modules -- >=20 selects 45 modules (1.7%), >=30 selects 29 (1.1%), >=50 selects 12 (0.4%).
# 30 sits an order of magnitude above the measured leaves (1-2) and below every measured
# hub (clients/base.py 35, bots/abstract.py 31, tools/abstract.py 151, conf.py 174).
DEFAULT_CORE_FANIN_THRESHOLD: int = 30
CORE_PATHS: tuple[str, ...] = (  # FEAT-620: regenerated by scripts/sdd/regen_core_paths.py
    "packages/ai-parrot-tools/src/parrot_tools/abstract.py",  # direct importers: 150
    "packages/ai-parrot-tools/src/parrot_tools/decorators.py",  # direct importers: 50
    "packages/ai-parrot-tools/src/parrot_tools/toolkit.py",  # direct importers: 104
    "packages/ai-parrot/src/parrot/_imports.py",  # direct importers: 53
    "packages/ai-parrot/src/parrot/auth/permission.py",  # direct importers: 39
    "packages/ai-parrot/src/parrot/bots/abstract.py",  # direct importers: 31
    "packages/ai-parrot/src/parrot/bots/flows/core/context.py",  # direct importers: 36
    "packages/ai-parrot/src/parrot/bots/flows/core/types.py",  # direct importers: 33
    "packages/ai-parrot/src/parrot/clients/base.py",  # direct importers: 35
    "packages/ai-parrot/src/parrot/clients/factory.py",  # direct importers: 39
    "packages/ai-parrot/src/parrot/conf.py",  # direct importers: 174
    "packages/ai-parrot/src/parrot/exceptions.py",  # direct importers: 32
    "packages/ai-parrot/src/parrot/flows/dev_loop/models/__init__.py",  # direct importers: 46
    "packages/ai-parrot/src/parrot/flows/dev_loop/session_state.py",  # direct importers: 31
    "packages/ai-parrot/src/parrot/knowledge/graphindex/schema.py",  # direct importers: 36
    "packages/ai-parrot/src/parrot/knowledge/ontology/schema.py",  # direct importers: 34
    "packages/ai-parrot/src/parrot/knowledge/wiki/project.py",  # direct importers: 32
    "packages/ai-parrot/src/parrot/knowledge/wiki/store.py",  # direct importers: 52
    "packages/ai-parrot/src/parrot/models/__init__.py",  # direct importers: 39
    "packages/ai-parrot/src/parrot/models/outputs.py",  # direct importers: 60
    "packages/ai-parrot/src/parrot/models/responses.py",  # direct importers: 43
    "packages/ai-parrot/src/parrot/outputs/a2ui/catalog/base.py",  # direct importers: 34
    "packages/ai-parrot/src/parrot/outputs/a2ui/models.py",  # direct importers: 52
    "packages/ai-parrot/src/parrot/stores/models.py",  # direct importers: 50
    "packages/ai-parrot/src/parrot/tools/abstract.py",  # direct importers: 151
    "packages/ai-parrot/src/parrot/tools/decorators.py",  # direct importers: 51
    "packages/ai-parrot/src/parrot/tools/toolkit.py",  # direct importers: 105
    "packages/ai-parrot/src/parrot/tools/working_memory/task_memory/models.py",  # direct importers: 30
    "packages/parrot-formdesigner/src/parrot_formdesigner/core/schema.py",  # direct importers: 49
)
# Measured safe under `-n auto` (same per-test outcome as serial, twice) — evidence:
# artifacts/logs/feat-604-xdist.md (FEAT-604 M3; supersedes the FEAT-563 S3 negative result).
# A distribution is added ONLY with a two-run comparison of its own; excluded distributions
# are listed in the evidence file with a recorded reason (and wall time when measured).
XDIST_SAFE_DISTRIBUTIONS: frozenset[str] = frozenset(
    {
        "ai-parrot-advisors",
        "ai-parrot-client-amazon",
        "ai-parrot-client-anthropic",
        "ai-parrot-client-gemma4",
        "ai-parrot-client-google",
        "ai-parrot-client-grok",
        "ai-parrot-client-groq",
        "ai-parrot-client-hf",
        "ai-parrot-client-jev",
        "ai-parrot-client-local",
        "ai-parrot-client-meta",
        "ai-parrot-client-moonshot",
        "ai-parrot-client-nvidia",
        "ai-parrot-client-openai",
        "ai-parrot-client-openrouter",
        "ai-parrot-client-vllm",
        "ai-parrot-client-zai",
        "ai-parrot-embeddings",
        "ai-parrot-loaders",
        "ai-parrot-openlit-bridge",
        "ai-parrot-pipelines",
        "ai-parrot-visualizations",
        "navrules",
    }
)
TIERS: tuple[str, ...] = ("task", "merge", "feature")


@dataclass(frozen=True)
class ScopePolicy:
    """Per-tier knobs; defaults are the module constants above."""

    impact_cap: int = DEFAULT_IMPACT_CAP
    impact_depth: int = DEFAULT_IMPACT_DEPTH
    core_fanin_threshold: int = DEFAULT_CORE_FANIN_THRESHOLD
    core_paths: tuple[str, ...] = CORE_PATHS
    xdist_safe: frozenset[str] = XDIST_SAFE_DISTRIBUTIONS
    marker_expression: str = AGENT_MARKER_EXPRESSION
