"""Regenerate `CORE_PATHS` for test_scope.policy from measured direct-importer counts.

FEAT-620. The previous 724-entry list was derived from a transitive fan-in metric
that saturated (see sdd/specs/test-scope-impact-tech-debt.spec.md). This script
re-derives it from the direct count so the list is reproducible rather than
archaeological.

Usage:
    python -m scripts.sdd.regen_core_paths --threshold 30
    python -m scripts.sdd.regen_core_paths --threshold 30 --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from parrot.flows.dev_loop.test_scope.impact import ImportIndex, module_aliases, module_name_for

REPO_ROOT = Path(__file__).resolve().parents[2]
POLICY_PATH = Path("packages/ai-parrot/src/parrot/flows/dev_loop/test_scope/policy.py")
START_MARKER = "CORE_PATHS: tuple[str, ...] = ("
END_MARKER = ")\n"

_ALIAS_PREFIXES = (
    ("packages/ai-parrot/src/parrot/tools/", "packages/ai-parrot-tools/src/parrot_tools/"),
    ("packages/ai-parrot-tools/src/parrot_tools/", "packages/ai-parrot/src/parrot/tools/"),
)


def direct_importers(index: ImportIndex, module: str) -> int:
    """Direct importer count, alias-expanded.

    Deliberately NOT `impact.source_fanin`: an independent copy makes the
    generator and the implementation cross-check each other, so a regression in
    `source_fanin` cannot regenerate a matching-but-wrong list that `--check`
    would then call green.
    """
    importers: set[str] = set()
    for alias in module_aliases(module):
        importers |= index.src_importers.get(alias, set())
    importers.discard(module)
    return len(importers)


def _alias_partner(path: str) -> str | None:
    """The `parrot/tools/<x>.py` <-> `parrot_tools/<x>.py` twin of `path`, if any."""
    for prefix, replacement in _ALIAS_PREFIXES:
        if path.startswith(prefix):
            return replacement + path[len(prefix) :]
    return None


def measure(root: Path, threshold: int) -> list[tuple[str, int]]:
    """Every source path at or above `threshold`, sorted by path. Alias pairs kept together."""
    index = ImportIndex.build(root)
    counts: dict[str, int] = {}
    for src_file in sorted(root.glob("packages/*/src/**/*.py")):
        rel = src_file.relative_to(root).as_posix()
        module = module_name_for(rel)
        if module is None:
            continue
        counts[rel] = direct_importers(index, module)

    kept = {path for path, count in counts.items() if count >= threshold}
    # A changed-file path can arrive under either spelling of an aliased module, so
    # retaining one half of a pair and dropping the other would make escalation depend
    # on which name git reported.
    for path in sorted(kept):
        partner = _alias_partner(path)
        if partner is not None and partner in counts:
            kept.add(partner)
    return [(path, counts[path]) for path in sorted(kept)]


def render(rows: list[tuple[str, int]]) -> str:
    """The `CORE_PATHS = (...)` literal, one entry per line with its measured count."""
    lines = [
        "CORE_PATHS: tuple[str, ...] = (  # FEAT-620: regenerated by scripts/sdd/regen_core_paths.py",
    ]
    for path, count in rows:
        lines.append(f'    "{path}",  # direct importers: {count}')
    lines.append(")")
    return "\n".join(lines) + "\n"


def current_literal(policy_text: str) -> str:
    """The `CORE_PATHS` tuple literal as it appears in `policy_text`, including its closing paren."""
    start = policy_text.index(START_MARKER)
    end = policy_text.index("\n" + END_MARKER, start) + 1 + len(END_MARKER)
    return policy_text[start:end]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--threshold", type=int, default=30)
    parser.add_argument("--check", action="store_true", help="exit 1 if policy.py is out of date")
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    args = parser.parse_args(argv)

    rows = measure(args.root, args.threshold)
    rendered = render(rows)
    if not args.check:
        sys.stdout.write(rendered)
        return 0

    policy_text = (args.root / POLICY_PATH).read_text(encoding="utf-8")
    if current_literal(policy_text) == rendered:
        print(f"CORE_PATHS up to date: {len(rows)} entries at threshold {args.threshold}")
        return 0
    print(
        f"CORE_PATHS is out of date: regeneration yields {len(rows)} entries at "
        f"threshold {args.threshold}. Re-run without --check and paste the output into "
        f"{POLICY_PATH}.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
