#!/usr/bin/env python3
"""Tailwind v4 CSS Generation Script for the A2UI `interactive-html` renderer.

AST-scans `interactive_html.py`'s literal `a2ui-*`/`ds-*`/`kpi-*`/`filter-*`/
`msf-*` class-name vocabulary (FEAT-522, spec §1 gap 2 / §3 Module 4), builds
a Tailwind v4 (CSS-first, no `tailwind.config.js`/PostCSS) `@apply` rule for
each EXISTING semantic selector, runs the Tailwind CLI, and writes the
compiled CSS to `design_system/tailwind.generated.css`. Markup class names
in `interactive_html.py` are never touched — this script only writes
`@apply` rules onto selectors that already exist in the renderer's output.

Mirrors `scripts/generate_tool_registry.py`'s CLI shape and `--check`
contract exactly (same repo, same "scan source, diff, fail in CI" pattern,
confirmed at spec time to be a real, working convention — spec §2, §8).

Usage:
    python scripts/generate_a2ui_css.py              # Generate/update the CSS
    python scripts/generate_a2ui_css.py --dry-run     # Show changes without writing
    python scripts/generate_a2ui_css.py --check       # CI mode: exit 1 if stale
    python scripts/generate_a2ui_css.py --verbose      # Verbose output
"""
from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
import tempfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
WORKSPACE_ROOT = Path(__file__).resolve().parent.parent

_VIZ_SRC = WORKSPACE_ROOT / "packages" / "ai-parrot-visualizations" / "src" / "parrot"

INTERACTIVE_HTML_PATH = _VIZ_SRC / "outputs" / "a2ui_renderers" / "interactive_html.py"

OUTPUT_CSS_PATH = (
    _VIZ_SRC / "outputs" / "formats" / "assets" / "design_system" / "tailwind.generated.css"
)

#: Every literal class-name token this script's safelist covers — mirrors
#: spec §1 gap 2's exact vocabulary (a2ui-*/ds-*/kpi-*/filter-*/msf-*).
_CLASS_TOKEN_RE = re.compile(r'(?:^|[\s"\'<>])((?:a2ui|ds|kpi|filter|msf)-[a-zA-Z0-9_-]+)')

#: A committed CSS selector line looks like `.some-class {` (one class per
#: rule, one rule per scanned class — see `_build_tailwind_entry`). Used by
#: `--check` to name which scanned class(es) drifted relative to what's
#: already committed.
_SELECTOR_HEADER_RE = re.compile(r"^\.([a-zA-Z0-9_-]+)\s*\{", re.MULTILINE)

_GENERATED_HEADER = (
    "/* AUTO-GENERATED by scripts/generate_a2ui_css.py — DO NOT EDIT BY HAND.\n"
    " * Source class vocabulary scanned from:\n"
    " *   packages/ai-parrot-visualizations/src/parrot/outputs/a2ui_renderers/interactive_html.py\n"
    " * Regenerate: python scripts/generate_a2ui_css.py\n"
    " * Verify freshness (CI): python scripts/generate_a2ui_css.py --check\n"
    " */\n"
)

#: Curated Tailwind v4 utility list per EXISTING `interactive_html.py`
#: selector, `@apply`-ed onto that selector unchanged (markup names never
#: renamed — spec §3 Module 4). Uses the design system's own CSS custom
#: properties (`--panel-bg`, `--neutral-text`, …, from
#: `design_system/__init__.py`'s `ThemeConfig.to_css_variables()`) via
#: Tailwind's arbitrary-value syntax for visual consistency with the rest of
#: `_BASE_CSS`/`_COMPONENTS_CSS`, rather than hardcoded Tailwind palette
#: colors. Exact utility choices are an implementation judgment call per
#: spec §3 Module 4 ("match the visual intent implied by each class's
#: existing usage context") — coverage, not pixel-perfect fidelity, is what
#: TASK-2794's coverage-audit test enforces.
SELECTOR_UTILITIES: dict[str, str] = {
    "a2ui-audio-desc": "text-sm text-[var(--neutral-muted)]",
    "a2ui-body": "text-sm leading-relaxed text-[var(--neutral-text)]",
    "a2ui-button": (
        "inline-flex items-center gap-1 rounded-[var(--radius)] bg-[var(--primary)] "
        "px-3 py-1.5 text-sm font-medium text-[var(--on-primary)]"
    ),
    "a2ui-card": (
        "rounded-[var(--radius)] border border-[var(--panel-border)] "
        "bg-[var(--panel-bg)] p-[var(--density-padding)]"
    ),
    "a2ui-chart-wrap": "flex flex-col gap-[var(--density-gap)]",
    "a2ui-col": "flex flex-col gap-[var(--density-gap)]",
    "a2ui-divider-h": "my-2 border-0 border-t border-[var(--panel-border)]",
    "a2ui-divider-v": "mx-2 inline-block w-px self-stretch bg-[var(--panel-border)]",
    "a2ui-field": "flex flex-col gap-0.5",
    "a2ui-field-label": "text-xs uppercase tracking-wide text-[var(--neutral-muted)]",
    "a2ui-field-value": "text-sm font-medium text-[var(--neutral-text)]",
    "a2ui-filter-empty": "py-2 text-sm italic text-[var(--neutral-muted)]",
    "a2ui-heading": "mb-1 text-base font-semibold text-[var(--neutral-text)]",
    "a2ui-icon": "inline-flex h-4 w-4 items-center justify-center",
    "a2ui-image": "block max-w-full rounded-[var(--radius)]",
    "a2ui-list-horizontal": "flex flex-row flex-wrap gap-2",
    "a2ui-list-vertical": "flex flex-col gap-2",
    "a2ui-metric-toggle": "mt-2 flex flex-wrap gap-2",
    "a2ui-modal": "fixed inset-0 flex items-center justify-center bg-black/40",
    "a2ui-row": "flex flex-row gap-[var(--density-gap)]",
    "a2ui-section": "mb-4 flex flex-col gap-2",
    "a2ui-subtitle": "mb-2 text-sm text-[var(--neutral-muted)]",
    "a2ui-tab-pane": "mt-2",
    "a2ui-table-notice": "mt-1 text-xs text-[var(--neutral-muted)]",
    "a2ui-table-pager": "mt-2 flex items-center justify-end gap-2",
    "a2ui-table-search": (
        "w-full max-w-xs rounded-[var(--radius)] border border-[var(--panel-border)] "
        "px-2 py-1 text-sm"
    ),
    "a2ui-table-wrap": "flex flex-col gap-2",
    "a2ui-tabs": "mb-2 flex flex-wrap gap-1",
    "a2ui-tabs-nav": "mb-2 flex flex-wrap gap-1 border-b border-[var(--panel-border)]",
    "a2ui-text": "text-sm text-[var(--neutral-text)]",
    "a2ui-title": "mb-1 text-lg font-bold text-[var(--neutral-text)]",
    "filter-bar": (
        "mb-3 flex flex-wrap items-center gap-2 rounded-[var(--radius)] "
        "border border-[var(--panel-border)] p-2"
    ),
    "filter-label": "mr-1 text-sm font-medium text-[var(--neutral-text)]",
    "filter-summary": "mt-1 w-full text-xs text-[var(--neutral-muted)]",
    "msf-actions": "mt-2 flex items-center justify-between gap-2",
    "msf-btn": (
        "inline-flex items-center gap-1 rounded-[var(--radius)] border "
        "border-[var(--panel-border)] bg-[var(--panel-bg)] px-2 py-1 text-sm"
    ),
    "msf-chip": (
        "mr-1 inline-flex items-center rounded-full bg-[var(--primary-light)] "
        "px-2 py-0.5 text-xs text-[var(--primary-dark)]"
    ),
    "msf-chips": "flex flex-wrap gap-1",
    "msf-label": "font-medium",
    "msf-opt": "flex items-center gap-2 px-2 py-1 text-sm",
    "msf-panel": (
        "absolute z-10 mt-1 rounded-[var(--radius)] border border-[var(--panel-border)] "
        "bg-[var(--panel-bg)] p-2"
    ),
    "msf-search": (
        "mb-2 w-full rounded-[var(--radius)] border border-[var(--panel-border)] "
        "px-2 py-1 text-sm"
    ),
}

#: Fallback for any FUTURE class the AST scan finds that isn't yet in
#: `SELECTOR_UTILITIES` above — guarantees every scanned class always gets
#: SOME rule (coverage, not curated styling) so `--check` still detects
#: drift deterministically rather than crashing on a KeyError.
_DEFAULT_UTILITIES = "block"

#: Classes the AST scan legitimately finds (they match the `kpi-*`
#: vocabulary) that are NOT part of spec §1 gap 2's base-primitive coverage
#: gap this script closes — they are already deliberately styled elsewhere
#: (`components.css` + per-layout overrides in `layout-*.css`) and must be
#: excluded from generation entirely, not just given a different utility
#: mapping. `kpi-grid` in particular: `components.css` keeps its base rule
#: a STATIC `repeat(4, 1fr)` specifically "so the print layout's composed
#: sheet never carries a responsive grid function" (its own comment) —
#: `layout-analytics.css` then opts back into
#: `repeat(auto-fit, minmax(...))` for screen surfaces only. A generated
#: Tailwind `grid-cols-*` utility for this selector would inject a
#: `minmax(...)` token into EVERY composed sheet (Tailwind's `grid-cols-N`
#: always compiles through `minmax(0, 1fr)`), including the print layout —
#: `_TAILWIND_CSS` sits before `layout_css` in `DesignSystem.stylesheet()`'s
#: concatenation, so cascade order alone doesn't hide it from a substring-
#: based test like `TestPrintLayout.test_no_auto_fit`. Verified empirically
#: (2026-09-03) generating with `grid-cols-2 md:grid-cols-4` before this
#: exclusion was added.
_ALREADY_STYLED_ELSEWHERE: frozenset[str] = frozenset({"kpi-grid"})


# ---------------------------------------------------------------------------
# AST-based class-name scanning
# ---------------------------------------------------------------------------
def _docstring_constant_ids(tree: ast.AST) -> set[int]:
    """Return the `id()`s of module/class/function docstring `Constant` nodes.

    Docstrings are prose, not markup — excluding them avoids false-positive
    class tokens picked up from human-readable text (e.g. a docstring
    mentioning "a live filter-state summary" would otherwise scan as the
    literal class token `filter-state`, which is never actually emitted).

    Args:
        tree: The parsed module AST.

    Returns:
        A set of `id()`s for each docstring's `ast.Constant` node.
    """
    ids: set[int] = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            body = node.body
            if (
                body
                and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)
            ):
                ids.add(id(body[0].value))
    return ids


def scan_classes(source_path: Path) -> set[str]:
    """AST-scan `source_path` for every literal class-name token.

    Walks every `ast.Constant` string in the module — including f-strings'
    (`ast.JoinedStr`) literal segments, since `ast.walk` recurses into them
    the same as any other nested node — and regex-extracts every
    `a2ui-*`/`ds-*`/`kpi-*`/`filter-*`/`msf-*` token found anywhere inside
    that string (not just whole-string matches, since real usage embeds
    multiple space-separated classes inside a single `class="..."`
    attribute literal). Docstrings are excluded (see
    `_docstring_constant_ids`).

    Args:
        source_path: The Python source file to scan.

    Returns:
        The deduplicated set of class-name tokens found.
    """
    tree = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
    docstring_ids = _docstring_constant_ids(tree)

    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, str):
            if id(node) in docstring_ids:
                continue
            found.update(_CLASS_TOKEN_RE.findall(node.value))
    return found


# ---------------------------------------------------------------------------
# Tailwind v4 CSS generation
# ---------------------------------------------------------------------------
def _build_tailwind_entry(classes: set[str]) -> str:
    """Build the Tailwind v4 CSS-first entry file content.

    Imports only `theme` (CSS custom properties `@apply` utilities like
    `gap-2` depend on, e.g. `--spacing`) and `utilities` (the utility
    definitions themselves) layers — deliberately NOT the full
    `@import "tailwindcss";` (which also pulls in Tailwind's global
    `preflight` reset). This design system already ships its own reset in
    `_BASE_CSS`; duplicating/conflicting with a second global reset here
    would be unwanted scope creep for a "cover missing base-primitive
    rules" feature (spec §1 gap 2).

    Args:
        classes: The scanned class-name tokens to generate one `@apply`
            rule for, one class per rule (sorted for deterministic output).

    Returns:
        The complete entry CSS text to feed the Tailwind CLI.
    """
    lines = [
        '@import "tailwindcss/theme" layer(theme);',
        '@import "tailwindcss/utilities" layer(utilities);',
        "",
    ]
    for cls in sorted(classes):
        utilities = SELECTOR_UTILITIES.get(cls, _DEFAULT_UTILITIES)
        lines.append(f".{cls} {{")
        lines.append(f"  @apply {utilities};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


#: Tailwind v4 packages installed on demand into an isolated temp directory
#: (never the repo's own `node_modules`/lockfiles — spec §7: "never a
#: runtime or install-time dependency" of `ai-parrot-visualizations`).
_TAILWIND_NPM_SPECS = ("tailwindcss@^4", "@tailwindcss/cli@^4")


def _run_tailwind_cli(entry_css: str, *, verbose: bool = False) -> str:
    """Run the Tailwind v4 standalone CLI over `entry_css` and return the output.

    Installs `tailwindcss`/`@tailwindcss/cli` (spec §7 External Dependencies:
    "Tailwind CLI (standalone binary) v4 — Compiles/purges utility CSS at
    CI/dev time only — never a runtime or install-time dependency") into an
    isolated temp directory — never the repo's own `node_modules` — so
    `@import "tailwindcss/theme"`/`"tailwindcss/utilities"` resolve
    regardless of the ambient environment's Node setup, then invokes the
    locally-installed CLI binary directly. Never imported by
    `ai-parrot-visualizations`'s own package code — this script is the only
    caller, and only at dev/CI time.

    Args:
        entry_css: The Tailwind v4 CSS-first entry file content (see
            `_build_tailwind_entry`).
        verbose: If True, print the exact CLI invocations.

    Returns:
        The compiled CSS text.

    Raises:
        RuntimeError: If `npm install` or the Tailwind CLI invocation fails
            (e.g. Node.js/npm not available in the current environment, no
            network access to the npm registry, or a malformed `@apply`
            rule).
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        input_path = tmp / "a2ui-input.css"
        output_path = tmp / "a2ui-output.css"
        input_path.write_text(entry_css, encoding="utf-8")

        install_cmd = ["npm", "install", "--no-save", "--silent", *_TAILWIND_NPM_SPECS]
        if verbose:
            print(f"Running: {' '.join(install_cmd)} (cwd={tmp})")
        install_result = subprocess.run(  # noqa: S603 — fixed argv, no shell
            install_cmd,
            cwd=tmp,
            capture_output=True,
            text=True,
            check=False,
        )
        if install_result.returncode != 0:
            raise RuntimeError(
                "Failed to install the Tailwind v4 CLI "
                f"(exit {install_result.returncode}):\n"
                f"{install_result.stdout}\n{install_result.stderr}"
            )

        cli_bin = tmp / "node_modules" / ".bin" / "tailwindcss"
        cmd = [str(cli_bin), "-i", str(input_path), "-o", str(output_path)]
        if verbose:
            print(f"Running: {' '.join(cmd)}")
        result = subprocess.run(  # noqa: S603 — fixed argv, no shell, dev/CI-only tool
            cmd,
            cwd=tmp,
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise RuntimeError(
                "Tailwind CLI failed "
                f"(exit {result.returncode}):\n{result.stdout}\n{result.stderr}"
            )
        return output_path.read_text(encoding="utf-8")


def generate_css(*, verbose: bool = False) -> tuple[str, set[str]]:
    """Scan, generate, and return the full `tailwind.generated.css` content.

    Args:
        verbose: If True, print the scanned class list and CLI invocation.

    Returns:
        `(generated_css_text, generated_classes)` — `generated_classes` is
        the scanned set MINUS `_ALREADY_STYLED_ELSEWHERE` (the classes this
        script actually writes an `@apply` rule for; TASK-2794's separate
        coverage-audit test is what verifies the excluded ones are still
        covered by `components.css`/`layout-*.css` instead).
    """
    classes = scan_classes(INTERACTIVE_HTML_PATH)
    if verbose:
        print(f"Scanned {len(classes)} class(es) from {INTERACTIVE_HTML_PATH}:")
        for cls in sorted(classes):
            print(f"  {cls}")
        if _ALREADY_STYLED_ELSEWHERE & classes:
            print(
                "  (excluded — already styled elsewhere: "
                f"{', '.join(sorted(_ALREADY_STYLED_ELSEWHERE & classes))})"
            )

    generated_classes = classes - _ALREADY_STYLED_ELSEWHERE
    entry_css = _build_tailwind_entry(generated_classes)
    compiled_css = _run_tailwind_cli(entry_css, verbose=verbose)
    return _GENERATED_HEADER + compiled_css, generated_classes


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate/validate the A2UI interactive-html Tailwind CSS coverage file"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would change without writing files",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="CI mode: exit 1 if the generated CSS is stale",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Verbose output",
    )
    args = parser.parse_args()

    if args.check:
        args.dry_run = True  # --check implies dry-run

    generated, classes = generate_css(verbose=args.verbose)
    existing = OUTPUT_CSS_PATH.read_text(encoding="utf-8") if OUTPUT_CSS_PATH.exists() else None

    if existing == generated:
        print(f"{OUTPUT_CSS_PATH.relative_to(WORKSPACE_ROOT)} is up to date.")
        return 0

    existing_selectors = _SELECTOR_HEADER_RE.findall(existing) if existing else []
    added = sorted(classes - set(existing_selectors))
    removed = sorted(set(existing_selectors) - classes)

    action = "Would update" if args.dry_run else "Updating"
    print(f"{action} {OUTPUT_CSS_PATH.relative_to(WORKSPACE_ROOT)}:")
    if added:
        print(f"  + new class(es) not yet covered: {', '.join(added)}")
    if removed:
        print(f"  - class(es) no longer emitted: {', '.join(removed)}")
    if not added and not removed:
        print("  (content differs — e.g. Tailwind CLI/theme output changed)")

    if not args.dry_run:
        OUTPUT_CSS_PATH.write_text(generated, encoding="utf-8")
        print(f"Wrote {OUTPUT_CSS_PATH.relative_to(WORKSPACE_ROOT)}.")

    if args.check:
        print(
            "\ntailwind.generated.css is STALE. Run: python scripts/generate_a2ui_css.py"
        )
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
