<script lang="ts">
  import { onDestroy } from "svelte";
  // Modular ECharts: pull `echarts/core` + only the lean set of charts and
  // components we register here, instead of the full `echarts` barrel (which
  // bundles every chart type, every component AND both renderers, ~1MB).
  // Options are generated by the backend/LLM, so any series type can arrive;
  // `resolveLib()` below lazy-loads the full build at runtime if (and only
  // if) an option uses a series type outside REGISTERED_SERIES. The common
  // case stays on the small core chunk; exotic charts still render.
  import * as echarts from "echarts/core";
  import {
    BarChart,
    LineChart,
    PieChart,
    ScatterChart,
    RadarChart,
    MapChart,
    GaugeChart,
    FunnelChart,
    HeatmapChart,
    CustomChart,
  } from "echarts/charts";
  import {
    TitleComponent,
    TooltipComponent,
    GridComponent,
    PolarComponent,
    RadarComponent,
    GeoComponent,
    LegendComponent,
    DataZoomComponent,
    DataZoomInsideComponent,
    DataZoomSliderComponent,
    VisualMapComponent,
    MarkPointComponent,
    MarkLineComponent,
    MarkAreaComponent,
    ToolboxComponent,
    GraphicComponent,
    AxisPointerComponent,
    DatasetComponent,
    TransformComponent,
  } from "echarts/components";
  import { LabelLayout, UniversalTransition } from "echarts/features";
  import { CanvasRenderer } from "echarts/renderers";

  echarts.use([
    BarChart,
    LineChart,
    PieChart,
    ScatterChart,
    RadarChart,
    MapChart,
    GaugeChart,
    FunnelChart,
    HeatmapChart,
    CustomChart,
    TitleComponent,
    TooltipComponent,
    GridComponent,
    PolarComponent,
    RadarComponent,
    GeoComponent,
    LegendComponent,
    DataZoomComponent,
    DataZoomInsideComponent,
    DataZoomSliderComponent,
    VisualMapComponent,
    MarkPointComponent,
    MarkLineComponent,
    MarkAreaComponent,
    ToolboxComponent,
    GraphicComponent,
    AxisPointerComponent,
    DatasetComponent,
    TransformComponent,
    LabelLayout,
    UniversalTransition,
    CanvasRenderer,
  ]);

  // Series types covered by the lean core registration above. Anything not
  // here (graph, tree, treemap, sunburst, sankey, themeRiver, parallel,
  // candlestick, boxplot, lines, pictorialBar, effectScatter, ...) triggers a
  // one-time lazy import of the full echarts build.
  const REGISTERED_SERIES = new Set([
    "bar",
    "line",
    "pie",
    "scatter",
    "radar",
    "map",
    "gauge",
    "funnel",
    "heatmap",
    "custom",
  ]);

  // Resolved to the full `echarts` build the first time an exotic series is
  // seen; cached for subsequent renders.
  let fullEchartsPromise: Promise<typeof echarts> | null = null;

  async function resolveLib(opts: EChartsOption): Promise<typeof echarts> {
    const needsFull = toArray(opts.series).some((entry) => {
      if (typeof entry !== "object" || !entry) return false;
      const type = (entry as Record<string, unknown>).type;
      return typeof type === "string" && !REGISTERED_SERIES.has(type);
    });
    if (!needsFull) return echarts;
    fullEchartsPromise ??= import("echarts").then(
      (m) => m as unknown as typeof echarts,
    );
    return fullEchartsPromise;
  }

  interface Props {
    options: any;
    theme?: string | object;
    className?: string;
    style?: string;
  }

  let {
    options,
    theme = "light",
    className = "",
    style = "width: 100%; height: 400px;",
  }: Props = $props();

  let chartContainer: HTMLDivElement;
  let chartInstance: echarts.EChartsType | null = null;

  type EChartsOption = Record<string, unknown>;

  function normalizeOptions(rawOptions: unknown): EChartsOption {
    if (typeof rawOptions === "string") {
      return JSON.parse(rawOptions) as EChartsOption;
    }
    return (rawOptions ?? {}) as EChartsOption;
  }

  function toArray(value: unknown): unknown[] {
    if (Array.isArray(value)) {
      return value;
    }
    return value != null ? [value] : [];
  }

  function hasWheelInteractiveFeatures(echartsOptions: EChartsOption): boolean {
    const dataZoomEntries = toArray(echartsOptions.dataZoom);
    const usesInsideDataZoom = dataZoomEntries.some((entry) => {
      if (typeof entry !== "object" || !entry) {
        return false;
      }

      const dataZoom = entry as Record<string, unknown>;
      if (dataZoom.type !== "inside") {
        return false;
      }

      const zoomOnWheel = dataZoom.zoomOnMouseWheel;
      const moveOnWheel = dataZoom.moveOnMouseWheel;
      const zoomEnabled =
        zoomOnWheel === undefined ? true : Boolean(zoomOnWheel);
      const moveEnabled =
        moveOnWheel === undefined ? true : Boolean(moveOnWheel);

      return zoomEnabled || moveEnabled;
    });

    if (usesInsideDataZoom) {
      return true;
    }

    const seriesEntries = toArray(echartsOptions.series);
    const hasRoamSeries = seriesEntries.some((entry) => {
      if (typeof entry !== "object" || !entry) {
        return false;
      }
      const roam = (entry as Record<string, unknown>).roam;
      return roam === true || roam === "scale" || roam === "move";
    });

    if (hasRoamSeries) {
      return true;
    }

    const geoEntries = toArray(echartsOptions.geo);
    return geoEntries.some((entry) => {
      if (typeof entry !== "object" || !entry) {
        return false;
      }
      const roam = (entry as Record<string, unknown>).roam;
      return roam === true || roam === "scale" || roam === "move";
    });
  }

  function withPatchedWheelListeners<T>(
    container: HTMLDivElement,
    fn: () => T,
  ): T {
    const originalAddEventListener = container.addEventListener;

    container.addEventListener = ((
      ...args: Parameters<HTMLDivElement["addEventListener"]>
    ) => {
      const [type, listener, opts] = args;
      if (
        (type === "wheel" || type === "mousewheel") &&
        (opts === undefined || opts === false)
      ) {
        return originalAddEventListener.call(container, type, listener, {
          passive: true,
        });
      }

      return originalAddEventListener.call(container, type, listener, opts);
    }) as HTMLDivElement["addEventListener"];

    try {
      return fn();
    } finally {
      container.addEventListener = originalAddEventListener;
    }
  }

  // Effect to initialize and update chart when options change
  // Using $effect to react to options changes in Svelte 5
  $effect(() => {
    if (chartContainer && options) {
      initOrUpdateChart();
    }
  });

  // Tracks the echarts build (core vs full) backing the live instance, and a
  // monotonic token so a slow full-build load can't clobber a newer render.
  let currentLib: typeof echarts = echarts;
  let renderToken = 0;

  async function initOrUpdateChart() {
    const safeOptions = normalizeOptions(options);
    const token = ++renderToken;
    const lib = await resolveLib(safeOptions);

    // Bail if the container was torn down or a newer render superseded us.
    if (!chartContainer || token !== renderToken) {
      return;
    }

    // An exotic series arrived after a core-rendered instance: dispose and
    // recreate with the resolved (full) build.
    if (chartInstance && lib !== currentLib) {
      chartInstance.dispose();
      chartInstance = null;
    }

    if (!chartInstance) {
      currentLib = lib;
      const initChart = () => lib.init(chartContainer, theme);
      chartInstance = hasWheelInteractiveFeatures(safeOptions)
        ? initChart()
        : withPatchedWheelListeners(chartContainer, initChart);
      // Add resize listener
      window.addEventListener("resize", handleResize);
    }

    chartInstance.setOption(safeOptions, true); // true = notMerge (replace checks)
  }

  function handleResize() {
    requestAnimationFrame(() => chartInstance?.resize());
  }

  let resizeObserver: ResizeObserver;

  onDestroy(() => {
    if (typeof window !== "undefined") {
      window.removeEventListener("resize", handleResize);
      resizeObserver?.disconnect();
    }
    chartInstance?.dispose();
    chartInstance = null;
  });

  // Watch container size changes
  $effect(() => {
    if (chartContainer) {
      resizeObserver = new ResizeObserver(() => {
        handleResize();
      });
      resizeObserver.observe(chartContainer);
    }
  });
</script>

<div
  bind:this={chartContainer}
  class={`echarts-container ${className}`}
  {style}
></div>
