"""Investment Memo persistence module.

This module provides storage and retrieval for InvestmentMemo artifacts
generated by the Finance deliberation pipeline.

Example:
    >>> from parrot.finance.memo_store import FileMemoStore, MemoEventType, get_memo_store
    >>> store = FileMemoStore(base_path="investment_memos")
    >>> await store.store(memo)
    >>> await store.log_event(memo.id, MemoEventType.EXECUTION_COMPLETED)

    >>> # Or use the factory (reads MEMO_STORE_PATH env var):
    >>> store = get_memo_store()
"""

import os

from .abstract import (
    AbstractMemoStore,
    MemoEvent,
    MemoEventType,
    MemoMetadata,
)
from .file_store import FileMemoStore


def get_memo_store(base_path: str | None = None) -> AbstractMemoStore:
    """Get a memo store instance.

    Creates a :class:`FileMemoStore` at the given path. If ``base_path`` is
    not provided, reads the ``MEMO_STORE_PATH`` environment variable,
    defaulting to ``"investment_memos"`` if unset.

    Args:
        base_path: Optional explicit path for memo storage. If ``None``,
            uses the ``MEMO_STORE_PATH`` environment variable or the default
            ``"investment_memos"`` directory.

    Returns:
        A ready-to-use :class:`FileMemoStore` instance.
    """
    resolved_path = base_path or os.getenv("MEMO_STORE_PATH", "investment_memos")
    return FileMemoStore(base_path=resolved_path)


__all__ = [
    "AbstractMemoStore",
    "FileMemoStore",
    "MemoEvent",
    "MemoEventType",
    "MemoMetadata",
    "get_memo_store",
]
