"""Wiki bookkeeper — index.md and log.md lifecycle management (FEAT-260).

Implements the bookkeeping layer of the LLM Wiki:

- **index.md** — extends OKF's ``generate_index_md()`` output with a
  wiki-specific header that includes source counts, category breakdown,
  and a last-updated timestamp.
- **log.md** — append-only operation chronicle.  Every entry is prefixed
  with a parseable ISO-8601 UTC timestamp and an operation tag so that
  tools can grep the log without parsing free-form text.

Log entry format::

    [2026-06-26T15:42:00Z] [INGEST] source: article.md, pages: 3
    [2026-06-26T15:43:12Z] [QUERY] question: "what is a neural network"
    [2026-06-26T15:50:00Z] [LINT] issues: 0

The bookkeeper does *not* hold any persistent state — all state lives on
disk in the wiki directory passed to each method call.  This keeps the
class stateless and safe to construct cheaply.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


class WikiBookkeeper:
    """Manages index.md and log.md bookkeeping files for a wiki.

    This class is intentionally stateless — wiki directory paths are
    passed to each method so the same instance can service multiple wikis.

    Example::

        bk = WikiBookkeeper()
        bk.log_operation(wiki_dir, "INGEST", "source: article.md, pages: 3")
        print(bk.read_log(wiki_dir, last_n=10))
    """

    INDEX_FILENAME: str = "index.md"
    LOG_FILENAME: str = "log.md"

    def __init__(self) -> None:
        """Initialise the bookkeeper."""
        self.logger: logging.Logger = logging.getLogger(__name__)

    # ------------------------------------------------------------------
    # index.md
    # ------------------------------------------------------------------

    def generate_index(
        self,
        tree: dict,
        tree_name: str,
        sources: Optional[list] = None,
        categories: Optional[list] = None,
    ) -> str:
        """Generate index.md content, extending OKF's output with wiki metadata.

        Calls ``generate_index_md(tree, tree_name)`` from the OKF projection
        module and prepends a wiki-specific summary block containing:
        - last-updated timestamp
        - number of tracked sources
        - category breakdown

        Falls back to a minimal header when the tree is empty or
        ``generate_index_md`` raises.

        Args:
            tree: OKF-enriched PageIndex tree dictionary.
            tree_name: PageIndex tree name used in OKF index links.
            sources: Optional list of source entries (for the count).
            categories: Optional list of category strings (for breakdown).

        Returns:
            A Markdown string suitable for writing to ``index.md``.
        """
        now_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        source_count = len(sources) if sources else 0

        # Build the wiki-specific header block
        header_lines = [
            "# Wiki Index",
            "",
            "<!-- Auto-generated by WikiBookkeeper. Do not edit. -->",
            "",
            f"**Last updated**: {now_str}",
            f"**Sources ingested**: {source_count}",
        ]

        if categories:
            header_lines.append("")
            header_lines.append("## Categories")
            for cat in sorted(set(str(c) for c in categories)):
                header_lines.append(f"- {cat}")

        header_lines.append("")
        header_lines.append("---")
        header_lines.append("")

        # Append OKF-generated content when the tree is available
        okf_content = ""
        if tree:
            try:
                from parrot.knowledge.pageindex.okf.projection import (  # pylint: disable=import-outside-toplevel
                    generate_index_md,
                )
                okf_content = generate_index_md(tree, tree_name)
            except Exception as exc:  # noqa: BLE001
                self.logger.warning(
                    "generate_index_md raised %s; skipping OKF content", exc
                )

        return "\n".join(header_lines) + (
            "\n" + okf_content if okf_content else ""
        )

    def write_index(
        self,
        wiki_dir: Path,
        tree: Optional[dict] = None,
        tree_name: str = "wiki",
        sources: Optional[list] = None,
        categories: Optional[list] = None,
    ) -> None:
        """Write (or overwrite) index.md in the wiki directory.

        Args:
            wiki_dir: Root directory of the wiki instance.
            tree: OKF tree dict; may be ``None`` for an empty wiki.
            tree_name: Tree name for OKF index links.
            sources: Source entries for count reporting.
            categories: Category strings for the breakdown section.
        """
        content = self.generate_index(
            tree or {}, tree_name, sources=sources, categories=categories
        )
        index_path = Path(wiki_dir) / self.INDEX_FILENAME
        index_path.parent.mkdir(parents=True, exist_ok=True)
        index_path.write_text(content, encoding="utf-8")
        self.logger.debug("Wrote index.md to %s", index_path)

    def rebuild_index(
        self,
        wiki_dir: Path,
        tree: Optional[dict] = None,
        tree_name: str = "wiki",
        sources: Optional[list] = None,
    ) -> str:
        """Regenerate index.md from current state and return the content.

        This is equivalent to ``write_index`` but also returns the content
        string so callers can inspect or log it.

        Args:
            wiki_dir: Root directory of the wiki instance.
            tree: OKF tree dict; may be ``None`` for an empty wiki.
            tree_name: Tree name for OKF index links.
            sources: Source entries for count reporting.

        Returns:
            The generated index.md content string.
        """
        self.write_index(wiki_dir, tree, tree_name, sources=sources)
        return (Path(wiki_dir) / self.INDEX_FILENAME).read_text(encoding="utf-8")

    # ------------------------------------------------------------------
    # log.md
    # ------------------------------------------------------------------

    def log_operation(
        self,
        wiki_dir: Path,
        operation: str,
        details: str,
        timestamp: Optional[str] = None,
    ) -> None:
        """Append a single operation entry to log.md.

        The entry format is::

            [<ISO-8601-UTC>] [<OPERATION>] <details>

        The log file is always opened in append mode and never truncated.

        Args:
            wiki_dir: Root directory of the wiki instance.
            operation: Short uppercase operation tag (e.g. ``"INGEST"``,
                ``"QUERY"``, ``"LINT"``).
            details: Human-readable details for this operation.
            timestamp: Optional pre-formatted ISO-8601 UTC timestamp.
                If ``None``, the current UTC time is used.
        """
        ts = timestamp or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        line = f"[{ts}] [{operation.upper()}] {details}\n"

        log_path = Path(wiki_dir) / self.LOG_FILENAME
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("a", encoding="utf-8") as fh:
            fh.write(line)
        self.logger.debug("Logged operation %s to %s", operation, log_path)

    def read_log(
        self,
        wiki_dir: Path,
        last_n: int = 50,
    ) -> str:
        """Return the last ``last_n`` lines from log.md.

        Args:
            wiki_dir: Root directory of the wiki instance.
            last_n: Maximum number of trailing lines to return.
                Pass ``0`` or a negative value to return all lines.

        Returns:
            A string containing up to ``last_n`` log lines.  Returns an
            empty string when the log file does not yet exist.
        """
        log_path = Path(wiki_dir) / self.LOG_FILENAME
        if not log_path.exists():
            return ""

        lines = log_path.read_text(encoding="utf-8").splitlines(keepends=True)
        if last_n and last_n > 0:
            lines = lines[-last_n:]
        return "".join(lines)
