"""Vault access layer — own toolkit, §11 init, §25 mirror, §8.1 link-fixup
(FEAT-481, spec Module 4).

**Additive-only (G11).** This module instantiates its **own**
``ObsidianToolkit`` (constructor arg — no edit to ``tools/obsidian.py``)
and never modifies FEAT-472's ``MeetingRegistry``. All vault writes made
by this subsystem go through :func:`build_vault_toolkit`'s instance.

**Registry location convention.** Neither ``sdd/specs/
fireflies-wiki-knowledgebase-agent.spec.md`` Module 1 nor this module's
own file list adds a new ``conf.py`` key for the registry directory (M2
fetch-gate and this module are independent, parallel tasks — spec
Worktree Strategy). Both derive the same directory purely from
:data:`~parrot.flows.wiki_ingest.conf.WIKI_KB_VAULT_PATH`:
``<vault>/Wiki/Registry`` (see :func:`registry_dir_for_vault`) — the same
folder the contract's §25 mirror file already lives in, so the
``MeetingRegistry``'s ``wiki.db`` and its human-readable mirror are
colocated. This mirrors FEAT-472's own ``FIREFLIES_REGISTRY_DIR`` default
(the wiki storage dir) without redefining it.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

from parrot.agents.meeting_registry import MeetingRegistry
from parrot.tools.obsidian import ObsidianToolkit

from . import conf

logger = logging.getLogger(__name__)

#: §4 — Claude-owned control files created (never overwritten) by §11 init.
_CONTROL_FILES: tuple[str, ...] = (
    "Wiki/index.md",
    "Wiki/overview.md",
    "Wiki/log.md",
    "Wiki/Review Queue.md",
    "Wiki/Registry/processed-sources.md",
)

#: §4 — folder-level index.md files created (never overwritten) by §11 init.
_FOLDER_INDEXES: tuple[str, ...] = (
    "Wiki/Sources/index.md",
    "Wiki/Entities/index.md",
    "Wiki/Concepts/index.md",
    "Wiki/Syntheses/index.md",
    "Wiki/Contradictions/index.md",
)

#: Default body for a freshly created control/index file — never
#: overwritten once it exists, so this is only ever seen once.
_DEFAULT_BODIES: dict[str, str] = {
    "Wiki/index.md": "# Wiki Index\n\nGenerated by the fireflies_wiki_kb agent's §11 initialization.\n",
    "Wiki/overview.md": "# Overview\n\nLiving summary of the knowledge base, maintained per contract §24.\n",
    "Wiki/log.md": "# Operation Log\n\nAppend-only log — see contract §33.\n",
    "Wiki/Review Queue.md": "# Review Queue\n\nHuman-judgment queue — see contract §26.\n",
    "Wiki/Registry/processed-sources.md": (
        "# Processed Source Registry\n\n"
        "Derived, human-readable mirror of the MeetingRegistry (`wiki.db`, "
        "FEAT-472) — see contract §25. Regenerated every ingest.\n"
    ),
}

_FOLDER_INDEX_TITLES: dict[str, str] = {
    "Wiki/Sources/index.md": "# Sources\n",
    "Wiki/Entities/index.md": "# Entities\n",
    "Wiki/Concepts/index.md": "# Concepts\n",
    "Wiki/Syntheses/index.md": "# Syntheses\n",
    "Wiki/Contradictions/index.md": "# Contradictions\n",
}

#: Matches an Obsidian wikilink/embed's target (group 2) — same shape as
#: parrot.interfaces.obsidian.parser.WikiLinkElement.pattern (§8.1
#: link-fixup rewrites the identical syntax the vault parser recognizes).
_WIKILINK_RE = re.compile(r"(!?\[\[)([^\[\]\|#\n]+)((?:#[^\[\]\|\n]+)?(?:\|[^\[\]\n]+)?\]\])")


def registry_dir_for_vault(vault_path: str | Path) -> Path:
    """Directory whose ``wiki.db`` backs this subsystem's ``MeetingRegistry``.

    Args:
        vault_path: The Obsidian vault root.

    Returns:
        ``<vault_path>/Wiki/Registry`` — see the module docstring.
    """
    return Path(vault_path) / "Wiki" / "Registry"


def build_vault_toolkit(vault_path: str | Path | None = None, **backend_kwargs: Any) -> ObsidianToolkit:
    """Construct this subsystem's own :class:`ObsidianToolkit` instance.

    Args:
        vault_path: Vault root (defaults to
            :data:`conf.WIKI_KB_VAULT_PATH`).
        **backend_kwargs: Forwarded to :class:`ObsidianToolkit`.

    Returns:
        A new :class:`ObsidianToolkit` scoped to the operations this
        subsystem needs (read/list/search/create/update/move/delete) —
        never a shared instance with any other agent (G11).

    Note:
        Contract §1 forbids ANY access to ``Private/`` — "Do not read,
        list, search, index, summarize, move, modify, or traverse it."
        The backend's default skip set only excludes
        ``.obsidian``/``.trash``/``.git``, so ``Private`` is added here
        explicitly. Without it, whole-vault ``search_notes``/
        ``catalog_notes`` (query, entity matching, lint, overview) would
        traverse and surface private notes. Mirrors the graph loader's
        ``extra_skip_patterns=["Private"]`` (Module 13).
    """
    extra_skip_patterns = list(backend_kwargs.pop("extra_skip_patterns", None) or [])
    if "Private" not in extra_skip_patterns:
        extra_skip_patterns.append("Private")
    return ObsidianToolkit(
        vault_path=str(vault_path or conf.WIKI_KB_VAULT_PATH),
        allowed_operations={"read", "list", "search", "create", "update", "move", "delete"},
        extra_skip_patterns=extra_skip_patterns,
        **backend_kwargs,
    )


def build_meeting_registry(vault_path: str | Path | None = None) -> MeetingRegistry:
    """Open this subsystem's own :class:`MeetingRegistry` instance.

    Args:
        vault_path: Vault root (defaults to
            :data:`conf.WIKI_KB_VAULT_PATH`).

    Returns:
        A :class:`MeetingRegistry` rooted at
        :func:`registry_dir_for_vault`.
    """
    return MeetingRegistry(registry_dir_for_vault(vault_path or conf.WIKI_KB_VAULT_PATH))


# ---------------------------------------------------------------------------
# §11 Initialization Workflow
# ---------------------------------------------------------------------------


async def initialize_vault(toolkit: ObsidianToolkit) -> list[str]:
    """§11 — create missing generated control/index files, idempotently.

    Never overwrites existing content (§11 step 4) and never touches
    ``Private/``/``.obsidian/`` (§11 steps 2/6). Creates no project,
    entity, concept, or source pages (§11 step 5).

    Args:
        toolkit: This subsystem's own :class:`ObsidianToolkit`.

    Returns:
        The vault-relative paths actually created this call (empty on a
        fully-initialized vault — idempotent).
    """
    created: list[str] = []
    for path in _CONTROL_FILES:
        if await _create_if_missing(toolkit, path, _DEFAULT_BODIES[path]):
            created.append(path)
    for path in _FOLDER_INDEXES:
        if await _create_if_missing(toolkit, path, _FOLDER_INDEX_TITLES[path]):
            created.append(path)
    return created


async def _create_if_missing(toolkit: ObsidianToolkit, path: str, body: str) -> bool:
    """Create ``path`` with ``body`` only if it does not already exist.

    Args:
        toolkit: This subsystem's own :class:`ObsidianToolkit`.
        path: Vault-relative path.
        body: Markdown body for a freshly created file.

    Returns:
        ``True`` if the file was created, ``False`` if it already existed.
    """
    try:
        await toolkit.read_note(path, include_content=False)
        return False
    except FileNotFoundError:
        await toolkit.create_note(path, body)
        return True


# ---------------------------------------------------------------------------
# §8.1 link-fixup — move_note() reports affected_backlinks but does not
# rewrite them.
# ---------------------------------------------------------------------------


async def fixup_links(
    toolkit: ObsidianToolkit,
    *,
    old_path: str,
    new_path: str,
    affected_backlinks: list[str],
) -> list[str]:
    """Rewrite ``[[wikilinks]]`` in every backlinking note after a move.

    ``ObsidianToolkit.move_note`` reports ``affected_backlinks`` (notes
    whose wikilinks referenced the old path/name) but does NOT rewrite
    them — this is the new §8.1 helper the spec calls for. Matches
    Obsidian's own resolution semantics (exact normalized path, else
    basename), so both ``[[Old Path/Old Name]]`` and ``[[Old Name]]``
    forms are rewritten.

    Args:
        toolkit: This subsystem's own :class:`ObsidianToolkit`.
        old_path: The note's vault-relative path before the move.
        new_path: The note's vault-relative path after the move.
        affected_backlinks: The ``affected_backlinks`` list
            ``move_note`` returned.

    Returns:
        The vault-relative paths actually rewritten (a subset of
        ``affected_backlinks`` — a backlink that no longer matches after
        re-reading is left untouched).
    """
    old_norm = _norm_target(old_path)
    old_stem = _basename(old_norm).lower()
    new_norm = _norm_target(new_path)

    def _sub(match: re.Match[str]) -> str:
        target = match.group(2).strip()
        norm_target = _norm_target(target)
        if norm_target == old_norm or norm_target.lower() == old_stem:
            return f"{match.group(1)}{new_norm}{match.group(3)}"
        return match.group(0)

    rewritten: list[str] = []
    for backlink_path in affected_backlinks:
        raw = await toolkit.vault.read_note(backlink_path)
        new_text, count = _WIKILINK_RE.subn(_sub, raw)
        if count:
            await toolkit.vault.write_note(backlink_path, new_text, overwrite=True)
            rewritten.append(backlink_path)
    return rewritten


def _norm_target(target: str) -> str:
    """Normalize a wikilink target the same way the vault index does."""
    text = target.strip()
    if text.lower().endswith(".md"):
        text = text[: -len(".md")]
    return text


def _basename(path: str) -> str:
    """POSIX basename without importing posixpath at call sites."""
    return path.rsplit("/", 1)[-1]


# ---------------------------------------------------------------------------
# §25 Processed Source Registry mirror — regenerated from the DB every
# ingest (R1). The DB (MeetingRegistry) is the authority; this mirror is
# derived-only and must never gate a fetch/skip decision.
# ---------------------------------------------------------------------------


async def regenerate_registry_mirror(toolkit: ObsidianToolkit, registry: MeetingRegistry) -> str:
    """Regenerate ``Wiki/Registry/processed-sources.md`` from the DB.

    Overwrite-regenerates the whole file every call — never hand-edited,
    so there is nothing to preserve (§25).

    Args:
        toolkit: This subsystem's own :class:`ObsidianToolkit`.
        registry: The :class:`MeetingRegistry` to mirror. Expects
            ``record.note_path`` to already hold this subsystem's own
            canonical ``Wiki/Sources/Meetings/...`` page path — set by
            the orchestrator's ``record_synced()`` call (spec Module 6)
            after the meeting-page renderer (Module 8) writes the page.

    Returns:
        The rendered Markdown body that was written.
    """
    records = await registry.all_records()
    lines = [
        "# Processed Source Registry",
        "",
        (
            "Derived, human-readable mirror of the MeetingRegistry (`wiki.db`, "
            "FEAT-472) — see contract §25. Regenerated every ingest; never "
            "hand-edit."
        ),
        "",
    ]
    for record in sorted(records, key=lambda r: r.meeting_date):
        page_link = f"Wiki/Sources/Meetings/{Path(record.note_path).stem}"
        lines.append(
            f"- `{record.external_id}` | meeting `{record.meeting_date}` | "
            f"summary `{record.summary_fingerprint or 'unknown'}` | "
            f"transcript `{record.fingerprint or 'unknown'}` | "
            f"[[{page_link}|Source Page]] | processed `{record.synced_at}`"
        )
    body = "\n".join(lines) + "\n"

    path = "Wiki/Registry/processed-sources.md"
    try:
        await toolkit.read_note(path, include_content=False)
        await toolkit.update_note(path, body, preserve_frontmatter=False)
    except FileNotFoundError:
        await toolkit.create_note(path, body)
    return body
